# WEB SCRAPING

Web scraping is a technique for extracting information from the internet automatically using our script that simulates human web surfing.

Web surfing help us extract large volumes of data from different websites.

When data is present on a local system we can use CSV,TxT format and use numpy,pandas,SQL to analyze them but when data is present online only then one method is using API but not all websites provide api to fetch data. So one choice is to manually visit,locate the desired data and extract the data in some file or DB, but it will fail when we need to extract large amount of data sat 100's of wesbite's data so another way is **Automated** manner => Web scraping. 

Eg: For my analysis I want to list down each and every educational institute in delhi, it can be school,college,coaching institute or a coaching centre , all this data can be found on just dial.com, we can visit to extract all data but manual extraction for all of these is still hectic so we will write a code to go and scrape justdial.com to tell all the desired data from this website and then save in some file for further analysis.

SCRAPING RULES:

1)  Check a Website's Terms and Condition before you scrape it-> not all websites allow scraping.
2)  Do not spam the website by making a lot of requests to a specific web page (don't slow down their server)
3)  Update your code time to time as websites generally change their page structure time to time.

LIBRARIES USES (in python):

1)  BeautifulSoup -> can parse html and XML documents 
2)  Selenium -> with which we can initiate different browser sessions -> automate browser activities 
3)  Scrapy

Process:

1)  Find the url that you want to scrape 
2)  Send an HTTP request to that URL and get the HTML as response 
3)  Parse the HTML content 
4)  Inspect the web page and find data that we want to extract 
5)  Extract required data and store it's data in the required format 

Note: Four major types of data are returned by server when called via get request : HTML,CSS,Javascript and Media content.
HTML will be majorly useful for extracting data since it has the main content (css is for styling, JS is for interaction and media content has images/videos and all), please revise HTML before proceeding

# BeautifulSoup

the main steps for analysis are 

1)  load the data=>  we can do using request.get(url) call which returns a string 
2) Parse the HTML => since string can't be processed properly so BeautifulSoup will parse it for us.
3)  Locate and extract the desired data

In [2]:
#pip install bs4 in command prompt 
# from bs4 package import it 
from bs4 import BeautifulSoup as bs

for now to practice we will use our own html page, which will be stored in our local system so we can't call it but we can pass that html code as a string to a variable html.
file:///C:/Users/user/Documents/Data%20science/webscrapinglearning.html

In [1]:
#loading the data done 
html= '''<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Testing Web Page</title>
</head>
<body>
	<h1> Web Scraping </h1>
	<p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping 
	</b>
</p>
<p id="def">
	You can read more about BeautifulSoup from 
	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
</p>
<p class="abc">
	<a href="https://Codingninjas.in"> Coding Ninjas </a>
</p>


</body>
</html>'''

Now to parse we need to give html data as string to the BeautifulSoup and provide the predefined parser

In [3]:
#step 2: parse data
data = bs(html,'html.parser')
print(data)

<!DOCTYPE html>

<html>
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Testing Web Page</title>
</head>
<body>
<h1> Web Scraping </h1>
<p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping
	</b>
</p>
<p id="def">
	You can read more about BeautifulSoup from
	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
</p>
<p class="abc">
<a href="https://Codingninjas.in"> Coding Ninjas </a>
</p>
</body>
</html>

In [6]:
# we can make it look more pretty using the method prettify() and print()
print(data.prettify())

<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>
   Testing Web Page
  </title>
 </head>
 <body>
  <h1>
   Web Scraping
  </h1>
  <p class="abc" id="first_para">
   Let's Start Learning
   <b>
    Web Scraping
   </b>
  </p>
  <p id="def">
   You can read more about BeautifulSoup from
   <a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/">
    here
   </a>
  </p>
  <p class="abc">
   <a href="https://Codingninjas.in">
    Coding Ninjas
   </a>
  </p>
 </body>
</html>

now for step 3: Extract data we can use many attributes and functions like:

1)  **.tag_name**   => provide the name of the tag and it will give complete details of that tag. In case there are multiple tags with same name present then it will return the first encounter one only from the top. In case wrong tag name is given it will not throw any error, will simply do nothing

In [8]:
data.title

In [9]:
data.head

<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Testing Web Page</title>
</head>

In [10]:
data.h1

In [11]:
#now in content we have three p tags available but it will give the first occurence only 
data.p

<p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping
	</b>
</p>

In [12]:
#if wrong tag name given it won't give any error => will do nothing 
data.pr

2)  **.tag.name** => will return name of the tag

In [13]:
data.title.name

'title'

3)  **.tag.string** => will return string data inside that tag

In [14]:
data.title.string

'Testing Web Page'

4)  **.tag.attrs**  => to get the attributes of a tag (like class and id present in that tag) as key:value pair in dict format, incase no attribute present it reurns empty dictionary

In [15]:
data.title.attrs  #since title tag has no attributes so empty dictory

{}

In [16]:
data.p.attrs

{'class': ['abc'], 'id': 'first_para'}

In [17]:
#getting values same as dict or use get()
data.p['id']

'first_para'

In [19]:
data.p.get('id')

'first_para'

#till now there were attributes now some methods :

1)  **get_text()** => to get all the text availale on webpage without any tag or attribute

In [20]:
data.get_text()

"\n\n\n\n\nTesting Web Page\n\n\n Web Scraping \n\n\t\tLet's Start Learning\n\t\n\t\tWeb Scraping \n\t\n\n\n\tYou can read more about BeautifulSoup from \n\t here \n\n\n Coding Ninjas \n\n\n"

2)  **.find()** => to find something from the page, takes string input of tag , works the same was as .tag_name attribute, so will give first encounter only and if wrong input given then no error and no ouput

In [21]:
data.find('p')

<p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping
	</b>
</p>

In [22]:
data.find('h2')

3)  **.find_all()** => to find all the occurences, same as find but for all occurences of a tag => ouput in form of a list

In [24]:
a=data.find_all('p')
a

[<p class="abc" id="first_para">
 		Let's Start Learning
 	<b>
 		Web Scraping
 	</b>
 </p>,
 <p id="def">
 	You can read more about BeautifulSoup from
 	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
 </p>,
 <p class="abc">
 <a href="https://Codingninjas.in"> Coding Ninjas </a>
 </p>]

In [25]:
type(a)

bs4.element.ResultSet

In [26]:
for i in a:
    print(i)

<p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping
	</b>
</p>
<p id="def">
	You can read more about BeautifulSoup from
	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
</p>
<p class="abc">
<a href="https://Codingninjas.in"> Coding Ninjas </a>
</p>

QUESTIONS

In [2]:
html = '<!DOCTYPE html><html><head><title>Learning Beautiful Soup</title></head>\
<body><h1> About Us </h1><div class = "first_div"><p>Coding Ninjas Website</p>\
<a href="https://www.codingninjas.in/">Link to Coding Ninjas Website</a>\
<ul><li>This</li><li>is</li><li>an</li><li>unordered</li><li>list.</li></ul>\
</div><p id = "template_p">This is a template paragraph tag</p>\
<a href = "https://www.facebook.com/codingninjas/">\
This is the link of our Facebook Page</a></body></html>'

In [4]:
from bs4 import BeautifulSoup as soup 
data= soup(html,'html.parser')
data

<!DOCTYPE html>
<html><head><title>Learning Beautiful Soup</title></head><body><h1> About Us </h1><div class="first_div"><p>Coding Ninjas Website</p><a href="https://www.codingninjas.in/">Link to Coding Ninjas Website</a><ul><li>This</li><li>is</li><li>an</li><li>unordered</li><li>list.</li></ul></div><p id="template_p">This is a template paragraph tag</p><a href="https://www.facebook.com/codingninjas/">This is the link of our Facebook Page</a></body></html>

In [29]:
#pretty data 
print(data.prettify())

<!DOCTYPE html>
<html>
 <head>
  <title>
   Learning Beautiful Soup
  </title>
 </head>
 <body>
  <h1>
   About Us
  </h1>
  <div class="first_div">
   <p>
    Coding Ninjas Website
   </p>
   <a href="https://www.codingninjas.in/">
    Link to Coding Ninjas Website
   </a>
   <ul>
    <li>
     This
    </li>
    <li>
     is
    </li>
    <li>
     an
    </li>
    <li>
     unordered
    </li>
    <li>
     list.
    </li>
   </ul>
  </div>
  <p id="template_p">
   This is a template paragraph tag
  </p>
  <a href="https://www.facebook.com/codingninjas/">
   This is the link of our Facebook Page
  </a>
 </body>
</html>

Print Body tag

You are given the HTML content of a webpage, your task is to :
Print all the contents of the body tag(including body tag)
NOTE : You are provided the HTML content inside variable html
Output Format :
<body>..........</body>

In [30]:
data.body

<body><h1> About Us </h1><div class="first_div"><p>Coding Ninjas Website</p><a href="https://www.codingninjas.in/">Link to Coding Ninjas Website</a><ul><li>This</li><li>is</li><li>an</li><li>unordered</li><li>list.</li></ul></div><p id="template_p">This is a template paragraph tag</p><a href="https://www.facebook.com/codingninjas/">This is the link of our Facebook Page</a></body>

Attributes of div tag

You are given the HTML content of a webpage, your task is to :
Print the name of all attributes of first div tag of the page
NOTE : You are provided the HTML content inside variable html
Output Format :
attribute_1
attribute_2
.
.

In [31]:
data= bs(html,'html.parser')
ans=data.div.attrs
for i in ans:
    print(i)

class

In [8]:
data.div.attrs

{'class': ['first_div']}

Strings of li

You are given the HTML content of a webpage, your task is to :
Print the strings(only text without tag names) of all li tags separated by a space
NOTE : You are provided the HTML content inside variable html

Output Format :
li_text1 li_text2 li_text3 ...

In [32]:
data= bs(html,'html.parser')
ans=data.find_all('li')
for i in ans:
    print(i.text,end=" ")

This is an unordered list.

href of A tag

You are given the HTML content of a webpage, your task is to :
Print the href of all the <a> tags on the page in different lines
NOTE : You are provided the HTML content inside variable html
Output Format :
a1_href
a2_href
a3_href
.

In [36]:
print(data.prettify())

<!DOCTYPE html>
<html>
 <head>
  <title>
   Learning Beautiful Soup
  </title>
 </head>
 <body>
  <h1>
   About Us
  </h1>
  <div class="first_div">
   <p>
    Coding Ninjas Website
   </p>
   <a href="https://www.codingninjas.in/">
    Link to Coding Ninjas Website
   </a>
   <ul>
    <li>
     This
    </li>
    <li>
     is
    </li>
    <li>
     an
    </li>
    <li>
     unordered
    </li>
    <li>
     list.
    </li>
   </ul>
  </div>
  <p id="template_p">
   This is a template paragraph tag
  </p>
  <a href="https://www.facebook.com/codingninjas/">
   This is the link of our Facebook Page
  </a>
 </body>
</html>

In [53]:
li=data.find_all('a')
ans=[]
for i in li :
    ans.append(i.attrs)

In [64]:
for j in range(len(ans)):
    print(ans[j]["href"])

https://www.codingninjas.in/
https://www.facebook.com/codingninjas/

In [5]:
#or 
a=data.find_all('a')
for i in a:
    print(i.attrs['href'])

https://www.codingninjas.in/
https://www.facebook.com/codingninjas/

NAVIGATING PARSE TREE 

1)  SEARCHING parse tree 
2)  GOING DOWN 
3)  GOING UP 
4)  GOING SIDEWAYS 
5)  GOING BACK AND FORTH

1) SEARCHING 


to find_all() function we can pass:  string,list,True(boolean),using id,using class and using css selector

In [4]:
#using string 
li=data.find_all('p')
for i in li:
    print(i)

<p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping
	</b>
</p>
<p id="def">
	You can read more about BeautifulSoup from
	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
</p>
<p class="abc">
<a href="https://Codingninjas.in"> Coding Ninjas </a>
</p>

In [7]:
#giving list of strings as input => returns each and every tag present in this list 
data.find_all(['p','a'])  #3 p tags and 2 anchor tags

[<p class="abc" id="first_para">
 		Let's Start Learning
 	<b>
 		Web Scraping
 	</b>
 </p>,
 <p id="def">
 	You can read more about BeautifulSoup from
 	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
 </p>,
 <a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>,
 <p class="abc">
 <a href="https://Codingninjas.in"> Coding Ninjas </a>
 </p>,
 <a href="https://Codingninjas.in"> Coding Ninjas </a>]

In [8]:
#boolean True => means I want to find out each and every tag present in this document,no filter all tags (not much useful)
data.find_all(True)

[<html>
 <head>
 <meta charset="utf-8"/>
 <meta content="width=device-width, initial-scale=1" name="viewport"/>
 <title>Testing Web Page</title>
 </head>
 <body>
 <h1> Web Scraping </h1>
 <p class="abc" id="first_para">
 		Let's Start Learning
 	<b>
 		Web Scraping
 	</b>
 </p>
 <p id="def">
 	You can read more about BeautifulSoup from
 	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
 </p>
 <p class="abc">
 <a href="https://Codingninjas.in"> Coding Ninjas </a>
 </p>
 </body>
 </html>,
 <head>
 <meta charset="utf-8"/>
 <meta content="width=device-width, initial-scale=1" name="viewport"/>
 <title>Testing Web Page</title>
 </head>,
 <meta charset="utf-8"/>,
 <meta content="width=device-width, initial-scale=1" name="viewport"/>,
 <title>Testing Web Page</title>,
 <body>
 <h1> Web Scraping </h1>
 <p class="abc" id="first_para">
 		Let's Start Learning
 	<b>
 		Web Scraping
 	</b>
 </p>
 <p id="def">
 	You can read more about BeautifulSoup from
 	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
 </p>
 <p class="abc">
 <a href="https://Codingninjas.in"> Coding Ninjas </a>
 </p>
 </body>,
 <h1> Web Scraping </h1>,
 <p class="abc" id="first_para">
 		Let's Start Learning
 	<b>
 		Web Scraping
 	</b>
 </p>,
 <b>
 		Web Scraping
 	</b>,
 <p id="def">
 	You can read more about BeautifulSoup from
 	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
 </p>,
 <a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>,
 <p class="abc">
 <a href="https://Codingninjas.in"> Coding Ninjas </a>
 </p>,
 <a href="https://Codingninjas.in"> Coding Ninjas </a>]

In [9]:
#for id  need to use keryword **id**
data.find_all(id="first_para")  #****************

[<p class="abc" id="first_para">
 		Let's Start Learning
 	<b>
 		Web Scraping
 	</b>
 </p>]

In [10]:
#using class need to use keyword **class_**
data.find_all(class_="abc")

[<p class="abc" id="first_para">
 		Let's Start Learning
 	<b>
 		Web Scraping
 	</b>
 </p>,
 <p class="abc">
 <a href="https://Codingninjas.in"> Coding Ninjas </a>
 </p>]

Note for css selector (. or #) but for that use data.select('') not find

2)  GOING DOWN

a)  Navigating using tag names , we can use nested tag names also 


b)  .string or .strings ( for one and for multiple child)


c)  .stripped_strings  (strips the space way from strings output)

d) .contents ( gives direct child output as list)

e) .children ( gives direct child but ouput is generator not a list)

f) .descendants  ( gives every child below given tag, text is also included as child , not just direct child)

In [11]:
#using tag name 
data.head

<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Testing Web Page</title>
</head>

In [12]:
#using nested tag 
data.head.title

In [ ]:
#here data.title is same as data.head.title but in situations like <h1><p> </p> <h1> and "<h2> <p> </p> <h2>" , 
#if i do data.p 
#then it will give only first p what if i only want second p? nested tag can help here by doing data.h2.p to get desired result

In [14]:
#b) using .string 
data.title.string  #** String is a child of title**

'Testing Web Page'

In [16]:
#what if i want string output of all p tags 
li=data.find_all('p')
for i in li:
    print(i.string)  #none output 
#that''s because .string only works well when it has only one child, in case of multiple child it gives none **

None
None
None

In [17]:
#so use .strings instead 
li=data.find_all('p')
for i in li:
    print(i.strings)  #gives generattor to iterate over #convert it to list

<generator object Tag._all_strings at 0x000001E828BAF190>
<generator object Tag._all_strings at 0x000001E828BAF190>
<generator object Tag._all_strings at 0x000001E828BAF190>

In [18]:
li=data.find_all('p')
for i in li:
    print(list(i.strings))  #considers spaces also as childs ***
    #seperate list for each p tag 
    #so use .strings for multiple children

["\n\t\tLet's Start Learning\n\t", '\n\t\tWeb Scraping \n\t', '\n']
['\n\tYou can read more about BeautifulSoup from \n\t', ' here ', '\n']
['\n', ' Coding Ninjas ', '\n']

In [19]:
#.stripped_strings 

for i in li:
    print(list(i.stripped_strings))  #**Removed space ** rest same as strings

["Let's Start Learning", 'Web Scraping']
['You can read more about BeautifulSoup from', 'here']
['Coding Ninjas']

In [20]:
#using .contents
data.html #gives all

<html>
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Testing Web Page</title>
</head>
<body>
<h1> Web Scraping </h1>
<p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping
	</b>
</p>
<p id="def">
	You can read more about BeautifulSoup from
	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
</p>
<p class="abc">
<a href="https://Codingninjas.in"> Coding Ninjas </a>
</p>
</body>
</html>

In [22]:
a=data.html.contents #to get direct child which for html are head and body 
print(len(a))
print(a)  #ncluding space in my case else child should be two : head and body

5
['\n', <head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Testing Web Page</title>
</head>, '\n', <body>
<h1> Web Scraping </h1>
<p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping
	</b>
</p>
<p id="def">
	You can read more about BeautifulSoup from
	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
</p>
<p class="abc">
<a href="https://Codingninjas.in"> Coding Ninjas </a>
</p>
</body>, '\n']

In [29]:
#using .children to get iterator output 
a=data.html.children 
print(a)
#print(list(a)) #this and 
print(len(list(a))) #this note not working together

<list_iterator object at 0x000001E828C3C910>
5

In [31]:
#using .descendants 
print(len(list(data.html.descendants))) #everything below html

35

In [33]:
list(data.html.descendants)

['\n',
 <head>
 <meta charset="utf-8"/>
 <meta content="width=device-width, initial-scale=1" name="viewport"/>
 <title>Testing Web Page</title>
 </head>,
 '\n',
 <meta charset="utf-8"/>,
 '\n',
 <meta content="width=device-width, initial-scale=1" name="viewport"/>,
 '\n',
 <title>Testing Web Page</title>,
 'Testing Web Page',
 '\n',
 '\n',
 <body>
 <h1> Web Scraping </h1>
 <p class="abc" id="first_para">
 		Let's Start Learning
 	<b>
 		Web Scraping
 	</b>
 </p>
 <p id="def">
 	You can read more about BeautifulSoup from
 	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
 </p>
 <p class="abc">
 <a href="https://Codingninjas.in"> Coding Ninjas </a>
 </p>
 </body>,
 '\n',
 <h1> Web Scraping </h1>,
 ' Web Scraping ',
 '\n',
 <p class="abc" id="first_para">
 		Let's Start Learning
 	<b>
 		Web Scraping
 	</b>
 </p>,
 "\n\t\tLet's Start Learning\n\t",
 <b>
 		Web Scraping
 	</b>,
 '\n\t\tWeb Scraping \n\t',
 '\n',
 '\n',
 <p id="def">
 	You can read more about BeautifulSoup from
 	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
 </p>,
 '\n\tYou can read more about BeautifulSoup from \n\t',
 <a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>,
 ' here ',
 '\n',
 '\n',
 <p class="abc">
 <a href="https://Codingninjas.in"> Coding Ninjas </a>
 </p>,
 '\n',
 <a href="https://Codingninjas.in"> Coding Ninjas </a>,
 ' Coding Ninjas ',
 '\n',
 '\n',
 '\n']

In [6]:
# to see what data is returned 
count=1
for i in data.descendants:
    print(count,i)
    count+=1

1 html
2 <html><head><title>Learning Beautiful Soup</title></head><body><h1> About Us </h1><div class="first_div"><p>Coding Ninjas Website</p><a href="https://www.codingninjas.in/">Link to Coding Ninjas Website</a><ul><li>This</li><li>is</li><li>an</li><li>unordered</li><li>list.</li></ul></div><p id="template_p">This is a template paragraph tag</p><a href="https://www.facebook.com/codingninjas/">This is the link of our Facebook Page</a></body></html>
3 <head><title>Learning Beautiful Soup</title></head>
4 <title>Learning Beautiful Soup</title>
5 Learning Beautiful Soup
6 <body><h1> About Us </h1><div class="first_div"><p>Coding Ninjas Website</p><a href="https://www.codingninjas.in/">Link to Coding Ninjas Website</a><ul><li>This</li><li>is</li><li>an</li><li>unordered</li><li>list.</li></ul></div><p id="template_p">This is a template paragraph tag</p><a href="https://www.facebook.com/codingninjas/">This is the link of our Facebook Page</a></body>
7 <h1> About Us </h1>
8  About Us
9 <div class="first_div"><p>Coding Ninjas Website</p><a href="https://www.codingninjas.in/">Link to Coding Ninjas Website</a><ul><li>This</li><li>is</li><li>an</li><li>unordered</li><li>list.</li></ul></div>
10 <p>Coding Ninjas Website</p>
11 Coding Ninjas Website
12 <a href="https://www.codingninjas.in/">Link to Coding Ninjas Website</a>
13 Link to Coding Ninjas Website
14 <ul><li>This</li><li>is</li><li>an</li><li>unordered</li><li>list.</li></ul>
15 <li>This</li>
16 This
17 <li>is</li>
18 is
19 <li>an</li>
20 an
21 <li>unordered</li>
22 unordered
23 <li>list.</li>
24 list.
25 <p id="template_p">This is a template paragraph tag</p>
26 This is a template paragraph tag
27 <a href="https://www.facebook.com/codingninjas/">This is the link of our Facebook Page</a>
28 This is the link of our Facebook Page

3)  GOING UP 

using .parent and .parents

In [34]:
data.title.parent  #gives parent of title that is head

<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Testing Web Page</title>
</head>

In [35]:
data.p.parent  #gives direct parent that is body here

<body>
<h1> Web Scraping </h1>
<p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping
	</b>
</p>
<p id="def">
	You can read more about BeautifulSoup from
	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
</p>
<p class="abc">
<a href="https://Codingninjas.in"> Coding Ninjas </a>
</p>
</body>

In [36]:
data.p.parents  #gives iterator

In [37]:
a=data.p.parents
print(list(a))   #gives for all 3 p tags thrice

[<body>
<h1> Web Scraping </h1>
<p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping
	</b>
</p>
<p id="def">
	You can read more about BeautifulSoup from
	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
</p>
<p class="abc">
<a href="https://Codingninjas.in"> Coding Ninjas </a>
</p>
</body>, <html>
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Testing Web Page</title>
</head>
<body>
<h1> Web Scraping </h1>
<p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping
	</b>
</p>
<p id="def">
	You can read more about BeautifulSoup from
	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
</p>
<p class="abc">
<a href="https://Codingninjas.in"> Coding Ninjas </a>
</p>
</body>
</html>, <!DOCTYPE html>

<html>
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Testing Web Page</title>
</head>
<body>
<h1> Web Scraping </h1>
<p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping
	</b>
</p>
<p id="def">
	You can read more about BeautifulSoup from
	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
</p>
<p class="abc">
<a href="https://Codingninjas.in"> Coding Ninjas </a>
</p>
</body>
</html>]

4)  GOING SIDEWAYS 

a)  next_sibling and previous_sibling 


b)next_siblings and previous_siblings

In [42]:
a=data.title.next_sibling 
print(type(a))
a

<class 'bs4.element.NavigableString'>

'\n'

In [39]:
data.title.previous_sibling

'\n'

In [41]:
a=data.title.next_siblings
print(a)
print(list(a))

<generator object PageElement.next_siblings at 0x000001E829046580>
['\n']

In [44]:
b=data.title.previous_siblings
print(b)
print(list(b))

<generator object PageElement.previous_siblings at 0x000001E8290469E0>
['\n', <meta content="width=device-width, initial-scale=1" name="viewport"/>, '\n', <meta charset="utf-8"/>, '\n']

5)  GOING BACK AND FORTH 

a)  .next_element and .previous_element 


b) .next_elements and .previous_elements

In [47]:
data.title.next_element

'Testing Web Page'

In [7]:
data.title.previous_element  #note text is also an element to soup not just tags

In [50]:
a=data.title.next_elements
print(a)
print(list(a))

<generator object PageElement.next_elements at 0x000001E829054970>
['Testing Web Page', '\n', '\n', <body>
<h1> Web Scraping </h1>
<p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping
	</b>
</p>
<p id="def">
	You can read more about BeautifulSoup from
	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
</p>
<p class="abc">
<a href="https://Codingninjas.in"> Coding Ninjas </a>
</p>
</body>, '\n', <h1> Web Scraping </h1>, ' Web Scraping ', '\n', <p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping
	</b>
</p>, "\n\t\tLet's Start Learning\n\t", <b>
		Web Scraping
	</b>, '\n\t\tWeb Scraping \n\t', '\n', '\n', <p id="def">
	You can read more about BeautifulSoup from
	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
</p>, '\n\tYou can read more about BeautifulSoup from \n\t', <a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>, ' here ', '\n', '\n', <p class="abc">
<a href="https://Codingninjas.in"> Coding Ninjas </a>
</p>, '\n', <a href="https://Codingninjas.in"> Coding Ninjas </a>, ' Coding Ninjas ', '\n', '\n', '\n']

In [51]:
b=data.title.previous_elements
print(b)
print(list(b))

<generator object PageElement.previous_elements at 0x000001E829054C10>
['\n', <meta content="width=device-width, initial-scale=1" name="viewport"/>, '\n', <meta charset="utf-8"/>, '\n', <head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Testing Web Page</title>
</head>, '\n', <html>
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Testing Web Page</title>
</head>
<body>
<h1> Web Scraping </h1>
<p class="abc" id="first_para">
		Let's Start Learning
	<b>
		Web Scraping
	</b>
</p>
<p id="def">
	You can read more about BeautifulSoup from
	<a href="https://www.crumming.com/software/BeautifulSoup/bs4/doc/"> here </a>
</p>
<p class="abc">
<a href="https://Codingninjas.in"> Coding Ninjas </a>
</p>
</body>
</html>, '\n', 'html']

QUESTIONS

Descendants and children

You are given the HTML content of a webpage, your task is to :
Print the difference between the number of descendants and the number of children of the html tag
NOTE : You are provided the HTML content inside variable html
Output Format :
difference

In [8]:
html = '<!DOCTYPE html><html><head><title>Navigate Parse Tree</title></head>\
<body><h1>This is your Assignment</h1><a href = "https://www.google.com">This is a link that will take you to Google</a>\
<ul><li><p> This question is given to test your knowledge of <b>Web Scraping</b></p>\
<p>Web scraping is a term used to describe the use of a program or algorithm to extract and process large amounts of data from the web.</p></li>\
<li id = "li2">This is an li tag given to you for scraping</li>\
<li>This li tag gives you the various ways to get data from a website\
<ol><li class = "list_or">Using API of the website</li><li>Scrape data using BeautifulSoup</li><li>Scrape data using Selenium</li>\
<li>Scrape data using Scrapy</li></ol></li>\
<li class = "list_or"><a href="https://www.crummy.com/software/BeautifulSoup/bs4/doc/">\
Clicking on this takes you to the documentation of BeautifulSoup</a>\
<a href="https://selenium-python.readthedocs.io/" id="anchor">Clicking on this takes you to the documentation of Selenium</a>\
</li></ul></body></html>'

In [9]:
from bs4 import BeautifulSoup as bs 
data=bs(html,'html.parser')
a=len(list(data.html.descendants))
b=len(list(data.html.children))#html is important
print(a-b)

32

Name of tags with ID

You are given the HTML content of a webpage, your task is to :
Print the name of all the tags in different lines that have an id attribute.
NOTE : You are provided the HTML content inside variable html
Output Format :
tag1
tag2
.
.

In [12]:
from bs4 import BeautifulSoup as soup
data=soup(html,'html.parser')

In [13]:
tags_with_id = data.find_all(attrs={"id": True})
for tag in tags_with_id:
    print(tag.name)

li
a

In [14]:
#or 
tags_with_id = data.find_all(id=True)
for tag in tags_with_id:
    print(tag.name)

li
a

Next Sibling

You are given the HTML content of a webpage, your task is to :
Print all content of the next siblings of the tag that have id as “li2”(in different lines)
NOTE : Content includes the complete html of tag
Output Format :
content_sibl1
content_sibl2
.
.

In [24]:

html = '<!DOCTYPE html><html><head><title>Navigate Parse Tree</title></head>\
<body><h1>This is your Assignment</h1><a href = "https://www.google.com">This is a link that will take you to Google</a>\
<ul><li><p> This question is given to test your knowledge of <b>Web Scraping</b></p>\
<p>Web scraping is a term used to describe the use of a program or algorithm to extract and process large amounts of data from the web.</p></li>\
<li id = "li2">This is an li tag given to you for scraping</li>\
<li>This li tag gives you the various ways to get data from a website\
<ol><li class = "list_or">Using API of the website</li><li>Scrape data using BeautifulSoup</li><li>Scrape data using Selenium</li>\
<li>Scrape data using Scrapy</li></ol></li>\
<li class = "list_or"><a href="https://www.crummy.com/software/BeautifulSoup/bs4/doc/">\
Clicking on this takes you to the documentation of BeautifulSoup</a>\
<a href="https://selenium-python.readthedocs.io/" id="anchor">Clicking on this takes you to the documentation of Selenium</a>\
</li></ul></body></html>'

## Print the required output in given format
from bs4 import BeautifulSoup as soup 

data=soup(html,'html.parser')

for i in list(data.find_all(id='li2')[0].next_siblings):
    print(i)

<li>This li tag gives you the various ways to get data from a website<ol><li class="list_or">Using API of the website</li><li>Scrape data using BeautifulSoup</li><li>Scrape data using Selenium</li><li>Scrape data using Scrapy</li></ol></li>
<li class="list_or"><a href="https://www.crummy.com/software/BeautifulSoup/bs4/doc/">Clicking on this takes you to the documentation of BeautifulSoup</a><a href="https://selenium-python.readthedocs.io/" id="anchor">Clicking on this takes you to the documentation of Selenium</a></li>

Parents of title

You are given the HTML content of a webpage, your task is to :
Print content of all the parents of the title tag(linewise)
NOTE : Content includes the whole HTML of the tag
Output Format :
parent1
parent2
parent3
.
.

In [28]:
for i in list(data.title.parents):
    print(i)

<head><title>Navigate Parse Tree</title></head>
<html><head><title>Navigate Parse Tree</title></head><body><h1>This is your Assignment</h1><a href="https://www.google.com">This is a link that will take you to Google</a><ul><li><p> This question is given to test your knowledge of <b>Web Scraping</b></p><p>Web scraping is a term used to describe the use of a program or algorithm to extract and process large amounts of data from the web.</p></li><li id="li2">This is an li tag given to you for scraping</li><li>This li tag gives you the various ways to get data from a website<ol><li class="list_or">Using API of the website</li><li>Scrape data using BeautifulSoup</li><li>Scrape data using Selenium</li><li>Scrape data using Scrapy</li></ol></li><li class="list_or"><a href="https://www.crummy.com/software/BeautifulSoup/bs4/doc/">Clicking on this takes you to the documentation of BeautifulSoup</a><a href="https://selenium-python.readthedocs.io/" id="anchor">Clicking on this takes you to the documentation of Selenium</a></li></ul></body></html>
<!DOCTYPE html>
<html><head><title>Navigate Parse Tree</title></head><body><h1>This is your Assignment</h1><a href="https://www.google.com">This is a link that will take you to Google</a><ul><li><p> This question is given to test your knowledge of <b>Web Scraping</b></p><p>Web scraping is a term used to describe the use of a program or algorithm to extract and process large amounts of data from the web.</p></li><li id="li2">This is an li tag given to you for scraping</li><li>This li tag gives you the various ways to get data from a website<ol><li class="list_or">Using API of the website</li><li>Scrape data using BeautifulSoup</li><li>Scrape data using Selenium</li><li>Scrape data using Scrapy</li></ol></li><li class="list_or"><a href="https://www.crummy.com/software/BeautifulSoup/bs4/doc/">Clicking on this takes you to the documentation of BeautifulSoup</a><a href="https://selenium-python.readthedocs.io/" id="anchor">Clicking on this takes you to the documentation of Selenium</a></li></ul></body></html>

Next Element

You are given the HTML content of a webpage, your task is to :
Print the string which is present inside the second anchor tag using BeautifulSoup's next_element property
Output Format :
string_next_element

In [32]:
data.find_all('a')[1].next_element   #2nd anchor elements next element

'Clicking on this takes you to the documentation of BeautifulSoup'

EXTRACTING DATA FROM FIRST WEB PAGE 

https://info.cern.ch/hypertext/WWW/TheProject.html

In [38]:
#load the required libraries 
from bs4 import BeautifulSoup as soup 
import requests

In [40]:
#load data 
response=requests.get("https://info.cern.ch/hypertext/WWW/TheProject.html")
response.status_code

200

In [66]:
#always check the type of response you are getting 
response.headers  #here content type : text/html

{'Date': 'Mon, 16 Oct 2023 12:29:47 GMT', 'Server': 'Apache', 'Last-Modified': 'Thu, 03 Dec 1992 08:37:20 GMT', 'ETag': '"8a9-291e721905000"', 'Accept-Ranges': 'bytes', 'Content-Length': '2217', 'Connection': 'close', 'Content-Type': 'text/html'}

In [44]:
html=response.text
#parse html data 
data=soup(html,'html.parser')

In [45]:
#extract data 
#print heading 
#using isnpect tool highlight the part you want using select tool and use that 
#on clicking WWW heading trhough select tool it shows it is inside h1 so 
data.h1

In [46]:
data.h1.string

'World Wide Web'

In [47]:
#to get the title 
data.title.string

'The World Wide Web project'

In [48]:
#to get complete text from this page 
data.get_text()

"\nThe World Wide Web project\n\n\n\nWorld Wide WebThe WorldWideWeb (W3) is a wide-area\nhypermedia information retrieval\ninitiative aiming to give universal\naccess to a large universe of documents.\nEverything there is online about\nW3 is linked directly or indirectly\nto this document, including an executive\nsummary of the project, Mailing lists\n, Policy , November's  W3  news ,\nFrequently Asked Questions .\n\nWhat's out there?\n Pointers to the\nworld's online information, subjects\n, W3 servers, etc.\nHelp\n on the browser you are using\nSoftware Products\n A list of W3 project\ncomponents and their current state.\n(e.g. Line Mode ,X11 Viola ,  NeXTStep\n, Servers , Tools , Mail robot ,\nLibrary )\nTechnical\n Details of protocols, formats,\nprogram internals etc\nBibliography\n Paper documentation\non  W3 and references.\nPeople\n A list of some people involved\nin the project.\nHistory\n A summary of the history\nof the project.\nHow can I help ?\n If you would like\nto support the web..\nGetting code\n Getting the code by\nanonymous FTP , etc.\n\n\n"

In [49]:
#using print for making it more readable 
print(data.get_text())

The World Wide Web project



World Wide WebThe WorldWideWeb (W3) is a wide-area
hypermedia information retrieval
initiative aiming to give universal
access to a large universe of documents.
Everything there is online about
W3 is linked directly or indirectly
to this document, including an executive
summary of the project, Mailing lists
, Policy , November's  W3  news ,
Frequently Asked Questions .

What's out there?
 Pointers to the
world's online information, subjects
, W3 servers, etc.
Help
 on the browser you are using
Software Products
 A list of W3 project
components and their current state.
(e.g. Line Mode ,X11 Viola ,  NeXTStep
, Servers , Tools , Mail robot ,
Library )
Technical
 Details of protocols, formats,
program internals etc
Bibliography
 Paper documentation
on  W3 and references.
People
 A list of some people involved
in the project.
History
 A summary of the history
of the project.
How can I help ?
 If you would like
to support the web..
Getting code
 Getting the code by
anonymous FTP , etc.

In [54]:
#extracting all hyperlinks from this web page 
for i in data.find_all('a'):
    print(i['href'])

WhatIs.html
Summary.html
Administration/Mailing/Overview.html
Policy.html
News/9211.html
FAQ/List.html
../DataSources/Top.html
../DataSources/bySubject/Overview.html
../DataSources/WWW/Servers.html
Help.html
Status.html
LineMode/Browser.html
Status.html#35
NeXT/WorldWideWeb.html
Daemon/Overview.html
Tools/Overview.html
MailRobot/Overview.html
Status.html#57
Technical.html
Bibliography.html
People.html
History.html
Helping.html
../README.html
LineMode/Defaults/Distribution.html

In [57]:
#let's try to extract links only from the specific section -> what's out there to getting a code and no links before that 
#in inspect tool we can say this part is actually a list under dl tag 
a=data.dl.find_all('a')
print(len(a))
for i in a:
    print(i['href'])

19
../DataSources/Top.html
../DataSources/bySubject/Overview.html
../DataSources/WWW/Servers.html
Help.html
Status.html
LineMode/Browser.html
Status.html#35
NeXT/WorldWideWeb.html
Daemon/Overview.html
Tools/Overview.html
MailRobot/Overview.html
Status.html#57
Technical.html
Bibliography.html
People.html
History.html
Helping.html
../README.html
LineMode/Defaults/Distribution.html

In [59]:
#to print only links in heading of these parts note point title are in dt and others in dd 
a=data.dl.find_all('dt')
len(a)

9

In [64]:
for i in a:
    print(i.a)

<a href="../DataSources/Top.html" name="44">What's out there?</a>
<a href="Help.html" name="46">Help</a>
<a href="Status.html" name="13">Software Products</a>
<a href="Technical.html" name="47">Technical</a>
<a href="Bibliography.html" name="40">Bibliography</a>
<a href="People.html" name="14">People</a>
<a href="History.html" name="15">History</a>
<a href="Helping.html" name="37">How can I help</a>
<a href="../README.html" name="48">Getting code</a>

BOOKS TO SCRAPE

link:https://books.toscrape.com/

In [67]:
#loading libraries
import requests 
from bs4 import BeautifulSoup as soup

In [68]:
#load the html data 
response=requests.get('https://books.toscrape.com/')
response

In [70]:
html=response.text
data=soup(html,'html.parser')
print(data.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="catalogue/category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="catalogue/category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>

In [71]:
#extracting title 
data.title

<title>
    All products | Books to Scrape - Sandbox
</title>

In [74]:
#to get main heading either see through inspect tool it's actually first link
data.a

In [75]:
#else 
data.header.a.string

'Books to Scrape'

In [77]:
#see on first page 20 books available -> lot of info for each book 
#title,rating,price etc
#let's extract details of this 1st book -> inspect tool ->see under class -> product_prod
b1=data.find(class_='product_pod')
b1.h3.a['title']

'A Light in the Attic'

In [78]:
b1.h3.a['href'] #actually relative url

'catalogue/a-light-in-the-attic_1000/index.html'

In [79]:
#to make complete url 
base_url='https://books.toscrape.com/'
print(base_url+b1.h3.a['href'])

https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html

In [82]:
#let's get hyperlinks for all the book 
books=data.find_all(class_='product_pod')
len(books)

20

In [83]:
for i in books:
    print(i.h3.a['href'])

catalogue/a-light-in-the-attic_1000/index.html
catalogue/tipping-the-velvet_999/index.html
catalogue/soumission_998/index.html
catalogue/sharp-objects_997/index.html
catalogue/sapiens-a-brief-history-of-humankind_996/index.html
catalogue/the-requiem-red_995/index.html
catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
catalogue/the-black-maria_991/index.html
catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html
catalogue/shakespeares-sonnets_989/index.html
catalogue/set-me-free_988/index.html
catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
catalogue/rip-it-up-and-start-again_986/index.html
catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
catalogue/olio_984/index.html
catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
catalogue/libertarianism-for-beginners_982/index.html
catalogue/its-only-the-himalayas_981/index.html

In [84]:
for i in books:
    print(base_url+i.h3.a['href'])

https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html
https://books.toscrape.com/catalogue/soumission_998/index.html
https://books.toscrape.com/catalogue/sharp-objects_997/index.html
https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html
https://books.toscrape.com/catalogue/the-requiem-red_995/index.html
https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
https://books.toscrape.com/catalogue/the-black-maria_991/index.html
https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html
https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html
https://books.toscrape.com/catalogue/set-me-free_988/index.html
https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html
https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
https://books.toscrape.com/catalogue/olio_984/index.html
https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html
https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html

Book Names from First Page

Print the title of all 20 books which are present on first page of this website.

 Book1 Name
 Book2 Name
 Book3 Name
 .
 .
 .

In [87]:
import requests 
from bs4 import BeautifulSoup as soup 
response=requests.get("https://books.toscrape.com/")
html=response.text 
data=soup(html,'html.parser')

In [101]:
books=data.find_all(class_='product_pod')
for i in books:
    print(i.h3.a['title'])

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas

Print the name of all categories which are present this website.

Output Format :
 Category1 Name
 Category2 Name
 Category3 Name
 .
 .
 .

In [124]:
#using inspect tool div class => side_categories => ul => nav nav-list, li =>ul => then all lists inside it

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="catalogue/category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="catalogue/category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>

In [171]:
import requests 
from bs4 import BeautifulSoup as soup 
response=requests.get("https://books.toscrape.com/")
html=response.text 
data=soup(html,'html.parser')


d={}
for i in list(data.find_all('ul')[1].li.ul.descendants):
    a=list(i.stripped_strings)
    for j in a:
        d[j]=d.get(j,0)
for k in d:
    print(k)

Travel
Mystery
Historical Fiction
Sequential Art
Classics
Philosophy
Romance
Womens Fiction
Fiction
Childrens
Religion
Nonfiction
Music
Default
Science Fiction
Sports and Games
Add a comment
Fantasy
New Adult
Young Adult
Science
Poetry
Paranormal
Art
Psychology
Autobiography
Parenting
Adult Fiction
Humor
Horror
History
Food and Drink
Christian Fiction
Business
Biography
Thriller
Contemporary
Spirituality
Academic
Self Help
Historical
Christian
Suspense
Short Stories
Novels
Health
Politics
Cultural
Erotica
Crime

In [172]:
#or 
categories_container = data.find('ul', class_='nav-list')

# Find all the list items (categories) within the container
categories = categories_container.find_all('li')

# Iterate through the categories and print their names
for category in categories[1:]:  #leaving first one since it will say "BOOKS" giving heading which is not needed
    category_name = category.a.text.strip()
    print(category_name)

Travel
Mystery
Historical Fiction
Sequential Art
Classics
Philosophy
Romance
Womens Fiction
Fiction
Childrens
Religion
Nonfiction
Music
Default
Science Fiction
Sports and Games
Add a comment
Fantasy
New Adult
Young Adult
Science
Poetry
Paranormal
Art
Psychology
Autobiography
Parenting
Adult Fiction
Humor
Horror
History
Food and Drink
Christian Fiction
Business
Biography
Thriller
Contemporary
Spirituality
Academic
Self Help
Historical
Christian
Suspense
Short Stories
Novels
Health
Politics
Cultural
Erotica
Crime

In [1]:
from bs4 import BeautifulSoup as soup 
import requests
response=requests.get("https://books.toscrape.com/")
response.status_code
html=response.text
data=soup(html,'html.parser')
for i in data.find_all(class_='side_categories'):
    print(list(i.stripped_strings)[1:])

['Travel', 'Mystery', 'Historical Fiction', 'Sequential Art', 'Classics', 'Philosophy', 'Romance', 'Womens Fiction', 'Fiction', 'Childrens', 'Religion', 'Nonfiction', 'Music', 'Default', 'Science Fiction', 'Sports and Games', 'Add a comment', 'Fantasy', 'New Adult', 'Young Adult', 'Science', 'Poetry', 'Paranormal', 'Art', 'Psychology', 'Autobiography', 'Parenting', 'Adult Fiction', 'Humor', 'Horror', 'History', 'Food and Drink', 'Christian Fiction', 'Business', 'Biography', 'Thriller', 'Contemporary', 'Spirituality', 'Academic', 'Self Help', 'Historical', 'Christian', 'Suspense', 'Short Stories', 'Novels', 'Health', 'Politics', 'Cultural', 'Erotica', 'Crime']

Links of all the pages 

Earlier we extracted data from first page only, this website has data of 1000 books -> available on 50 different pages. To get info about all the books we need to load data from all the pages 

The browse url should change for every get request, if you inspect the next button you will see the relative url to next pages each time you click on next , 
for page 2 it has class="next" href= "catalogue/page-2.html"  and after that just /page3.html , /page4.html. 
so 1st relative url need to have catalogue/ too in the link, other don't -> we can use an if else situation or we can once see what loads for books.toscrape.com/catalogue/page1.html rather than just for books.toscrape.com, page loading is same so better to use former one as base url

Note: if you think rather than extracting url from next we can just do base url+ page[i] i randing from 2 to 50 then this can only work here since page naming is systematic but what if page 2 has url named xyz and 3 has abc, so in that case better to make base url + relative url extracted from next button.

Also here we know limit for loop is 50 since total pages are 50 but in case we don't know then we can use while response.status_code= success that is 200

In [2]:
import requests
from bs4 import BeautifulSoup as soup

#making a list of all urls
all_urls=["https://books.toscrape.com/catalogue/page-1.html"]
current_page='https://books.toscrape.com/catalogue/page-1.html'
base_url='https://books.toscrape.com/catalogue/'
response=requests.get(current_page)
while response.status_code==200:
    data=soup(response.text,'html.parser')
    next_page=data.find(class_='next')
    next_page_url=base_url+next_page.a['href']
    print(next_page_url)
    all_urls.append(next_page_url)
    current_page=next_page_url
    response=requests.get(current_page)

https://books.toscrape.com/catalogue/page-2.html
https://books.toscrape.com/catalogue/page-3.html
https://books.toscrape.com/catalogue/page-4.html
https://books.toscrape.com/catalogue/page-5.html
https://books.toscrape.com/catalogue/page-6.html
https://books.toscrape.com/catalogue/page-7.html
https://books.toscrape.com/catalogue/page-8.html
https://books.toscrape.com/catalogue/page-9.html
https://books.toscrape.com/catalogue/page-10.html
https://books.toscrape.com/catalogue/page-11.html
https://books.toscrape.com/catalogue/page-12.html
https://books.toscrape.com/catalogue/page-13.html
https://books.toscrape.com/catalogue/page-14.html
https://books.toscrape.com/catalogue/page-15.html
https://books.toscrape.com/catalogue/page-16.html
https://books.toscrape.com/catalogue/page-17.html
https://books.toscrape.com/catalogue/page-18.html
https://books.toscrape.com/catalogue/page-19.html
https://books.toscrape.com/catalogue/page-20.html
https://books.toscrape.com/catalogue/page-21.html
https://books.toscrape.com/catalogue/page-22.html
https://books.toscrape.com/catalogue/page-23.html
https://books.toscrape.com/catalogue/page-24.html
https://books.toscrape.com/catalogue/page-25.html
https://books.toscrape.com/catalogue/page-26.html
https://books.toscrape.com/catalogue/page-27.html
https://books.toscrape.com/catalogue/page-28.html
https://books.toscrape.com/catalogue/page-29.html
https://books.toscrape.com/catalogue/page-30.html
https://books.toscrape.com/catalogue/page-31.html
https://books.toscrape.com/catalogue/page-32.html
https://books.toscrape.com/catalogue/page-33.html
https://books.toscrape.com/catalogue/page-34.html
https://books.toscrape.com/catalogue/page-35.html
https://books.toscrape.com/catalogue/page-36.html
https://books.toscrape.com/catalogue/page-37.html
https://books.toscrape.com/catalogue/page-38.html
https://books.toscrape.com/catalogue/page-39.html
https://books.toscrape.com/catalogue/page-40.html
https://books.toscrape.com/catalogue/page-41.html
https://books.toscrape.com/catalogue/page-42.html
https://books.toscrape.com/catalogue/page-43.html
https://books.toscrape.com/catalogue/page-44.html
https://books.toscrape.com/catalogue/page-45.html
https://books.toscrape.com/catalogue/page-46.html
https://books.toscrape.com/catalogue/page-47.html
https://books.toscrape.com/catalogue/page-48.html
https://books.toscrape.com/catalogue/page-49.html
https://books.toscrape.com/catalogue/page-50.html

AttributeError: 'NoneType' object has no attribute 'a'

In [3]:
#error at the end due to next_page=data.find(class_='next') since there is no class named next at the last page so to fix that:
all_urls=["https://books.toscrape.com/catalogue/page-1.html"]
current_page='https://books.toscrape.com/catalogue/page-1.html'
base_url='https://books.toscrape.com/catalogue/'
response=requests.get(current_page)
while response.status_code==200:
    data=soup(response.text,'html.parser')
    next_page=data.find(class_='next')
    if next_page is None:
        break
    next_page_url=base_url+next_page.a['href']
    print(next_page_url)
    all_urls.append(next_page_url)
    current_page=next_page_url
    response=requests.get(current_page)

https://books.toscrape.com/catalogue/page-2.html
https://books.toscrape.com/catalogue/page-3.html
https://books.toscrape.com/catalogue/page-4.html
https://books.toscrape.com/catalogue/page-5.html
https://books.toscrape.com/catalogue/page-6.html
https://books.toscrape.com/catalogue/page-7.html
https://books.toscrape.com/catalogue/page-8.html
https://books.toscrape.com/catalogue/page-9.html
https://books.toscrape.com/catalogue/page-10.html
https://books.toscrape.com/catalogue/page-11.html
https://books.toscrape.com/catalogue/page-12.html
https://books.toscrape.com/catalogue/page-13.html
https://books.toscrape.com/catalogue/page-14.html
https://books.toscrape.com/catalogue/page-15.html
https://books.toscrape.com/catalogue/page-16.html
https://books.toscrape.com/catalogue/page-17.html
https://books.toscrape.com/catalogue/page-18.html
https://books.toscrape.com/catalogue/page-19.html
https://books.toscrape.com/catalogue/page-20.html
https://books.toscrape.com/catalogue/page-21.html
https://books.toscrape.com/catalogue/page-22.html
https://books.toscrape.com/catalogue/page-23.html
https://books.toscrape.com/catalogue/page-24.html
https://books.toscrape.com/catalogue/page-25.html
https://books.toscrape.com/catalogue/page-26.html
https://books.toscrape.com/catalogue/page-27.html
https://books.toscrape.com/catalogue/page-28.html
https://books.toscrape.com/catalogue/page-29.html
https://books.toscrape.com/catalogue/page-30.html
https://books.toscrape.com/catalogue/page-31.html
https://books.toscrape.com/catalogue/page-32.html
https://books.toscrape.com/catalogue/page-33.html
https://books.toscrape.com/catalogue/page-34.html
https://books.toscrape.com/catalogue/page-35.html
https://books.toscrape.com/catalogue/page-36.html
https://books.toscrape.com/catalogue/page-37.html
https://books.toscrape.com/catalogue/page-38.html
https://books.toscrape.com/catalogue/page-39.html
https://books.toscrape.com/catalogue/page-40.html
https://books.toscrape.com/catalogue/page-41.html
https://books.toscrape.com/catalogue/page-42.html
https://books.toscrape.com/catalogue/page-43.html
https://books.toscrape.com/catalogue/page-44.html
https://books.toscrape.com/catalogue/page-45.html
https://books.toscrape.com/catalogue/page-46.html
https://books.toscrape.com/catalogue/page-47.html
https://books.toscrape.com/catalogue/page-48.html
https://books.toscrape.com/catalogue/page-49.html
https://books.toscrape.com/catalogue/page-50.html

All Book Names

Print the title of all books which are present on first 10 pages of this website.
Output Format :
 Book1 Name
 Book2 Name
 Book3 Name
 .
 .

In [5]:
allPages = ['http://books.toscrape.com/catalogue/page-1.html',
            'http://books.toscrape.com/catalogue/page-2.html',
            'http://books.toscrape.com/catalogue/page-3.html',
            'http://books.toscrape.com/catalogue/page-4.html',
            'http://books.toscrape.com/catalogue/page-5.html',
            'http://books.toscrape.com/catalogue/page-6.html',
            'http://books.toscrape.com/catalogue/page-7.html',
            'http://books.toscrape.com/catalogue/page-8.html',
            'http://books.toscrape.com/catalogue/page-9.html',
            'http://books.toscrape.com/catalogue/page-10.html']

import requests
from bs4 import BeautifulSoup as soup 
bookstitle=[]
for i in range(10):
    response = requests.get(allPages[i])
    data=soup(response.text,'html.parser')
    booksdata=data.find_all(class_='product_pod')
    for j in booksdata:
        bookstitle.append(j.h3.a['title'])
for d in bookstitle:
    print(d)

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas
In Her Wake
How Music Works
Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More
Chase Me (Paris Nights #2)
Black Dust
Birdsong: A Story in Pictures
America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana
Aladdin and His Wonderful Lamp
Worlds Elsewhere: Journeys Around Shakespeareâs Globe
Wall and Piece
The Four Agreements: A Practical Guide to Personal Freedom
The Five Love Languages: How to Express Heartfelt Commitment to Your Mate
The Elephant Tree
The Bear and the Piano
Sophie's World
Penny Maybe
Maude (1883-1993):She Grew Up with the country
In a Dark, Dark Wood
Behind Closed Doors
You can't bury them all: Poems
Slow States of Collapse: Poems
Reasons to Stay Alive
Private Paris (Private #10)
#HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.
Without Borders (Wanderlove #1)
When We Collided
We Love You, Charlie Freeman
Untitled Collection: Sabbath Poems 2014
Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness
Unicorn Tracks
Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink
Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRoNiCLE #2)
Throwing Rocks at the Google Bus: How Growth Became the Enemy of Prosperity
This One Summer
Thirst
The Torch Is Passed: A Harding Family Story
The Secret of Dreadwillow Carse
The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!
The Past Never Ends
The Natural History of Us (The Fine Art of Pretending #2)
The Nameless City (The Nameless City #1)
The Murder That Never Was (Forensic Instincts #5)
The Most Perfect Thing: Inside (and Outside) a Bird's Egg
The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy
The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing
The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer
The Gutsy Girl: Escapades for Your Life of Epic Adventure
The Electric Pencil: Drawings from Inside State Hospital No. 3
The Death of Humanity: and the Case for Life
The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life
The Art Forger
The Age of Genius: The Seventeenth Century and the Birth of the Modern Mind
The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution
Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up
Soul Reader
Security
Saga, Volume 6 (Saga (Collected Editions) #6)
Saga, Volume 5 (Saga (Collected Editions) #5)
Reskilling America: Learning to Labor in the Twenty-First Century
Rat Queens, Vol. 3: Demons (Rat Queens (Collected Editions) #11-15)
Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)
Princess Between Worlds (Wide-Awake Princess #5)
Pop Gun War, Volume 1: Gift
Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics
Patience
Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)
orange: The Complete Collection 1 (orange: The Complete Collection #1)
Online Marketing for Busy Authors: A Step-By-Step Guide
On a Midnight Clear
Obsidian (Lux #1)
My Paris Kitchen: Recipes and Stories
Masks and Shadows
Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed
Lumberjanes, Vol. 2: Friendship to the Max (Lumberjanes #5-8)
Lumberjanes, Vol. 1: Beware the Kitten Holy (Lumberjanes #1-4)
Lumberjanes Vol. 3: A Terrible Plan (Lumberjanes #9-12)
Layered: Baking, Building, and Styling Spectacular Cakes
Judo: Seven Steps to Black Belt (an Introductory Guide for Beginners)
Join
In the Country We Love: My Family Divided
Immunity: How Elie Metchnikoff Changed the Course of Modern Medicine
I Hate Fairyland, Vol. 1: Madly Ever After (I Hate Fairyland (Compilations) #1-5)
I am a Hero Omnibus Volume 1
How to Be Miserable: 40 Strategies You Already Use
Her Backup Boyfriend (The Sorensen Family #1)
Giant Days, Vol. 2 (Giant Days #5-8)
Forever and Forever: The Courtship of Henry Longfellow and Fanny Appleton
First and First (Five Boroughs #3)
Fifty Shades Darker (Fifty Shades #2)
Everydata: The Misinformation Hidden in the Little Data You Consume Every Day
Don't Be a Jerk: And Other Practical Advice from Dogen, Japan's Greatest Zen Master
Danganronpa Volume 1
Crown of Midnight (Throne of Glass #2)
Codename Baboushka, Volume 1: The Conclave of Death
Camp Midnight
Call the Nurse: True Stories of a Country Nurse on a Scottish Isle
Burning
Bossypants
Bitch Planet, Vol. 1: Extraordinary Machine (Bitch Planet (Collected Editions))
Avatar: The Last Airbender: Smoke and Shadow, Part 3 (Smoke and Shadow #3)
Algorithms to Live By: The Computer Science of Human Decisions
A World of Flavor: Your Gluten Free Passport
A Piece of Sky, a Grain of Rice: A Memoir in Four Meditations
A Murder in Time
A Flight of Arrows (The Pathfinders #2)
A Fierce and Subtle Poison
A Court of Thorns and Roses (A Court of Thorns and Roses #1)
(Un)Qualified: How God Uses Broken People to Do Big Things
You Are What You Love: The Spiritual Power of Habit
William Shakespeare's Star Wars: Verily, A New Hope (William Shakespeare's Star Wars #4)
Tuesday Nights in 1980
Tracing Numbers on a Train
Throne of Glass (Throne of Glass #1)
Thomas Jefferson and the Tripoli Pirates: The Forgotten War That Changed American History
Thirteen Reasons Why
The White Cat and the Monk: A Retelling of the Poem âPangur BÃ¡nâ
The Wedding Dress
The Vacationers
The Third Wave: An Entrepreneurâs Vision of the Future
The Stranger
The Shadow Hero (The Shadow Hero)
The Secret (The Secret #1)
The Regional Office Is Under Attack!
The Psychopath Test: A Journey Through the Madness Industry
The Project
The Power of Now: A Guide to Spiritual Enlightenment
The Omnivore's Dilemma: A Natural History of Four Meals
The Nerdy Nummies Cookbook: Sweet Treats for the Geek in All of Us
The Murder of Roger Ackroyd (Hercule Poirot #4)
The Mistake (Off-Campus #2)
The Matchmaker's Playbook (Wingmen Inc. #1)
The Love and Lemons Cookbook: An Apple-to-Zucchini Celebration of Impromptu Cooking
The Long Shadow of Small Ghosts: Murder and Memory in an American City
The Kite Runner
The House by the Lake
The Glittering Court (The Glittering Court #1)
The Girl on the Train
The Genius of Birds
The Emerald Mystery
The Cookies & Cups Cookbook: 125+ sweet & savory recipes reminding you to Always Eat Dessert First
The Bridge to Consciousness: I'm Writing the Bridge Between Science and Our Old and New Beliefs.
The Artist's Way: A Spiritual Path to Higher Creativity
The Art of War
The Argonauts
The 10% Entrepreneur: Live Your Startup Dream Without Quitting Your Day Job
Suddenly in Love (Lake Haven #1)
Something More Than This
Soft Apocalypse
So You've Been Publicly Shamed
Shoe Dog: A Memoir by the Creator of NIKE
Shobu Samurai, Project Aryoku (#3)
Secrets and Lace (Fatal Hearts #1)
Scarlett Epstein Hates It Here
Romero and Juliet: A Tragic Tale of Love and Zombies
Redeeming Love
Poses for Artists Volume 1 - Dynamic and Sitting Poses: An Essential Reference for Figure Drawing and the Human Form
Poems That Make Grown Women Cry
Nightingale, Sing
Night Sky with Exit Wounds
Mrs. Houdini
Modern Romance
Miss Peregrineâs Home for Peculiar Children (Miss Peregrineâs Peculiar Children #1)
Louisa: The Extraordinary Life of Mrs. Adams
Little Red
Library of Souls (Miss Peregrineâs Peculiar Children #3)
Large Print Heart of the Pride
I Had a Nice Time And Other Lies...: How to find love & sh*t like that
Hollow City (Miss Peregrineâs Peculiar Children #2)
Grumbles
Full Moon over Noahâs Ark: An Odyssey to Mount Ararat and Beyond
Frostbite (Vampire Academy #2)
Follow You Home
First Steps for New Christians (Print Edition)
Finders Keepers (Bill Hodges Trilogy #2)
Fables, Vol. 1: Legends in Exile (Fables #1)
Eureka Trivia 6.0
Drive: The Surprising Truth About What Motivates Us
Done Rubbed Out (Reightman & Bailey #1)
Doing It Over (Most Likely To #1)
Deliciously Ella Every Day: Quick and Easy Recipes for Gluten-Free Snacks, Packed Lunches, and Simple Meals

Store Data in CSV

A dedicated link is present for each book amongs 1000s on website, on going to link we can see more details abt the book like title,qty in stock,price description etc.

Let's create a dataframe of Links to websites link,title,price and qty in stock (this is not visible on homepage)

In [4]:
#ecxtracting the details for one book first 
#make a get req to homepage-> extract the book link -> extract data from that link 
#pre req 
import requests
from bs4 import BeautifulSoup as soup

In [11]:
response=requests.get('https://books.toscrape.com/')
data=soup(response.text,'html.parser')
base_url='https://books.toscrape.com/'
b1=base_url+data.find(class_='product_pod').h3.a['href']
b1  #dedicated website extracted

'https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html'

In [20]:
#now extracting required info from dedicated website 
response=requests.get(b1)
data=soup(response.text,'html.parser')
link=b1
title=data.h1.string
price=data.find(class_='price_color').string
#qty has multiple childs
qtylist=list(data.find(class_='instock availability').stripped_strings)
qty=qtylist[0]

'In stock (22 available)'

In [21]:
#printing all 
print(title)
print(link)
print(price)
print(qty)   #need to remove other text from qty and price to just get numbers

A Light in the Attic
https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
Â£51.77
In stock (22 available)

Regular Expressions (regX) using python re library  we can easily obtain data from strings

re.search() => takes two arguments pattern and the given string.
used along with group () to get the output rather than the object 

[] -> set of patterns or character i want to match 
\d -> number from 0 to 9 in string given ( only gives first occurence )=> backslash !!
+ -> plus operator to indicate to consider all occurences 
. -> here represents to include '.' as well we can add more as per requirement 

will gi ve string output so typecaste it to int and float

In [26]:
import re

In [28]:
a=re.search('\d',price)
print(a)

<re.Match object; span=(2, 3), match='5'>

In [31]:
a=re.search('\d',price).group()
print(a)

5

In [32]:
#to get all occurence
re.search('\d+',price).group()

'51'

In [33]:
#to include .
re.search('[\d.]+',price).group()

'51.77'

In [34]:
price=float(re.search('[\d.]+',price).group())
qty=int(re.search('\d+',qty).group())

In [35]:
print(title)
print(link)
print(price)
print(qty)

A Light in the Attic
https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
51.77
22

In [39]:
#making a 2d list which we can conver to dataframe later
bookdetails=[]
bookdetails.append([title,link,price,qty])
#just two visualize appending twice 
bookdetails.append([title,link,price,qty])
bookdetails

[['A Light in the Attic',
  'https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html',
  51.77,
  22],
 ['A Light in the Attic',
  'https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html',
  51.77,
  22]]

In [40]:
import pandas as pd 

df=pd.DataFrame(bookdetails,columns=['Title','Link','Price','Quantity In Stock'])
df

,Title,Link,Price,Quantity In Stock
0,A Light in the Attic,https://books.toscrape.com/catalogue/a-light-i...,51.77,22
1,A Light in the Attic,https://books.toscrape.com/catalogue/a-light-i...,51.77,22

In [43]:
#to extract to csv 
df.to_csv('books.csv',index=False)  #to avoid index getting download

Book Details

Find and print the details of all books which are present on first 2 pages of this website.
All details include - Title of the book, book page url, Price (in float, without any currency or extra symbol), and quantity in stock (in integer). Save all the details in a dataframe and print in the required format.
Note: Remove the Trailing Zeros from price of book.

Output Format :
 Book1_Title Book1_Link Book1_Price Book1_Quantity
 Book2_Title Book2_Link Book2_Price Book2_Quantity
 Book3_Title Book3_Link Book3_Price Book3_Quantity
 .
 .
 .

In [2]:
#doing for first two pages 
import requests
from bs4 import BeautifulSoup as soup 
import re 
import pandas as pd

allPages = ['http://books.toscrape.com/catalogue/page-1.html',
            'http://books.toscrape.com/catalogue/page-2.html']

column_names = ['Title', 'Link', 'Price', 'Quantity in Stock']
base_url='https://books.toscrape.com/catalogue/'
book_urls=[]
for i in range(2):
    response=requests.get(allPages[i])
    data=soup(response.text,'html.parser')
    a=data.find_all(class_='product_pod')
    for k in range(len(a)):
        alink=base_url+a[k].h3.a['href']
        book_urls.append(alink)
book_urls

['https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html',
 'https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html',
 'https://books.toscrape.com/catalogue/soumission_998/index.html',
 'https://books.toscrape.com/catalogue/sharp-objects_997/index.html',
 'https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html',
 'https://books.toscrape.com/catalogue/the-requiem-red_995/index.html',
 'https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html',
 'https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html',
 'https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html',
 'https://books.toscrape.com/catalogue/the-black-maria_991/index.html',
 'https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html',
 'https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html',
 'https://books.toscrape.com/catalogue/set-me-free_988/index.html',
 'https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html',
 'https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html',
 'https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html',
 'https://books.toscrape.com/catalogue/olio_984/index.html',
 'https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html',
 'https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html',
 'https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html',
 'https://books.toscrape.com/catalogue/in-her-wake_980/index.html',
 'https://books.toscrape.com/catalogue/how-music-works_979/index.html',
 'https://books.toscrape.com/catalogue/foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html',
 'https://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html',
 'https://books.toscrape.com/catalogue/black-dust_976/index.html',
 'https://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html',
 'https://books.toscrape.com/catalogue/americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html',
 'https://books.toscrape.com/catalogue/aladdin-and-his-wonderful-lamp_973/index.html',
 'https://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html',
 'https://books.toscrape.com/catalogue/wall-and-piece_971/index.html',
 'https://books.toscrape.com/catalogue/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html',
 'https://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html',
 'https://books.toscrape.com/catalogue/the-elephant-tree_968/index.html',
 'https://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html',
 'https://books.toscrape.com/catalogue/sophies-world_966/index.html',
 'https://books.toscrape.com/catalogue/penny-maybe_965/index.html',
 'https://books.toscrape.com/catalogue/maude-1883-1993she-grew-up-with-the-country_964/index.html',
 'https://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html',
 'https://books.toscrape.com/catalogue/behind-closed-doors_962/index.html',
 'https://books.toscrape.com/catalogue/you-cant-bury-them-all-poems_961/index.html']

In [11]:
#now extracting required data 
books_details=[]
for l in book_urls:
    response=requests.get(l)
    
    if response.status_code==200:
        data=soup(response.text,'html.parser')
        link=l
        title=data.h1.string
        price=data.find(class_='price_color').string
    
        qtylist=list(data.find(class_='instock availability').stripped_strings)
        qty=qtylist[0]
        price=float((re.search('[\d.]+',price)).group())
        price = "{:.2f}".format(price)
        qty=int((re.search('\d+',qty)).group())
        

        books_details.append([title,link,price,qty])
books_details

[['A Light in the Attic',
  'https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html',
  '51.77',
  22],
 ['Tipping the Velvet',
  'https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html',
  '53.74',
  20],
 ['Soumission',
  'https://books.toscrape.com/catalogue/soumission_998/index.html',
  '50.10',
  20],
 ['Sharp Objects',
  'https://books.toscrape.com/catalogue/sharp-objects_997/index.html',
  '47.82',
  20],
 ['Sapiens: A Brief History of Humankind',
  'https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html',
  '54.23',
  20],
 ['The Requiem Red',
  'https://books.toscrape.com/catalogue/the-requiem-red_995/index.html',
  '22.65',
  19],
 ['The Dirty Little Secrets of Getting Your Dream Job',
  'https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html',
  '33.34',
  19],
 ['The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
  'https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html',
  '17.93',
  19],
 ['The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  'https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html',
  '22.60',
  19],
 ['The Black Maria',
  'https://books.toscrape.com/catalogue/the-black-maria_991/index.html',
  '52.15',
  19],
 ['Starving Hearts (Triangular Trade Trilogy, #1)',
  'https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html',
  '13.99',
  19],
 ["Shakespeare's Sonnets",
  'https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html',
  '20.66',
  19],
 ['Set Me Free',
  'https://books.toscrape.com/catalogue/set-me-free_988/index.html',
  '17.46',
  19],
 ["Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)",
  'https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html',
  '52.29',
  19],
 ['Rip it Up and Start Again',
  'https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html',
  '35.02',
  19],
 ['Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
  'https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html',
  '57.25',
  19],
 ['Olio',
  'https://books.toscrape.com/catalogue/olio_984/index.html',
  '23.88',
  19],
 ['Mesaerion: The Best Science Fiction Stories 1800-1849',
  'https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html',
  '37.59',
  19],
 ['Libertarianism for Beginners',
  'https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html',
  '51.33',
  19],
 ["It's Only the Himalayas",
  'https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html',
  '45.17',
  19],
 ['In Her Wake',
  'https://books.toscrape.com/catalogue/in-her-wake_980/index.html',
  '12.84',
  19],
 ['How Music Works',
  'https://books.toscrape.com/catalogue/how-music-works_979/index.html',
  '37.32',
  19],
 ['Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More',
  'https://books.toscrape.com/catalogue/foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html',
  '30.52',
  19],
 ['Chase Me (Paris Nights #2)',
  'https://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html',
  '25.27',
  19],
 ['Black Dust',
  'https://books.toscrape.com/catalogue/black-dust_976/index.html',
  '34.53',
  19],
 ['Birdsong: A Story in Pictures',
  'https://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html',
  '54.64',
  19],
 ["America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana",
  'https://books.toscrape.com/catalogue/americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html',
  '22.50',
  19],
 ['Aladdin and His Wonderful Lamp',
  'https://books.toscrape.com/catalogue/aladdin-and-his-wonderful-lamp_973/index.html',
  '53.13',
  19],
 ['Worlds Elsewhere: Journeys Around Shakespeareâ\x80\x99s Globe',
  'https://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html',
  '40.30',
  18],
 ['Wall and Piece',
  'https://books.toscrape.com/catalogue/wall-and-piece_971/index.html',
  '44.18',
  18],
 ['The Four Agreements: A Practical Guide to Personal Freedom',
  'https://books.toscrape.com/catalogue/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html',
  '17.66',
  18],
 ['The Five Love Languages: How to Express Heartfelt Commitment to Your Mate',
  'https://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html',
  '31.05',
  18],
 ['The Elephant Tree',
  'https://books.toscrape.com/catalogue/the-elephant-tree_968/index.html',
  '23.82',
  18],
 ['The Bear and the Piano',
  'https://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html',
  '36.89',
  18],
 ["Sophie's World",
  'https://books.toscrape.com/catalogue/sophies-world_966/index.html',
  '15.94',
  18],
 ['Penny Maybe',
  'https://books.toscrape.com/catalogue/penny-maybe_965/index.html',
  '33.29',
  18],
 ['Maude (1883-1993):She Grew Up with the country',
  'https://books.toscrape.com/catalogue/maude-1883-1993she-grew-up-with-the-country_964/index.html',
  '18.02',
  18],
 ['In a Dark, Dark Wood',
  'https://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html',
  '19.63',
  18],
 ['Behind Closed Doors',
  'https://books.toscrape.com/catalogue/behind-closed-doors_962/index.html',
  '52.22',
  18],
 ["You can't bury them all: Poems",
  'https://books.toscrape.com/catalogue/you-cant-bury-them-all-poems_961/index.html',
  '33.63',
  17]]

In [12]:
df=pd.DataFrame(books_details,columns=column_names)
df

,Title,Link,Price,Quantity in Stock
0,A Light in the Attic,https://books.toscrape.com/catalogue/a-light-i...,51.77,22
1,Tipping the Velvet,https://books.toscrape.com/catalogue/tipping-t...,53.74,20
2,Soumission,https://books.toscrape.com/catalogue/soumissio...,50.10,20
3,Sharp Objects,https://books.toscrape.com/catalogue/sharp-obj...,47.82,20
4,Sapiens: A Brief History of Humankind,https://books.toscrape.com/catalogue/sapiens-a...,54.23,20
5,The Requiem Red,https://books.toscrape.com/catalogue/the-requi...,22.65,19
6,The Dirty Little Secrets of Getting Your Dream...,https://books.toscrape.com/catalogue/the-dirty...,33.34,19
7,The Coming Woman: A Novel Based on the Life of...,https://books.toscrape.com/catalogue/the-comin...,17.93,19
8,The Boys in the Boat: Nine Americans and Their...,https://books.toscrape.com/catalogue/the-boys-...,22.60,19
9,The Black Maria,https://books.toscrape.com/catalogue/the-black...,52.15,19
10,"Starving Hearts (Triangular Trade Trilogy, #1)",https://books.toscrape.com/catalogue/starving-...,13.99,19
11,Shakespeare's Sonnets,https://books.toscrape.com/catalogue/shakespea...,20.66,19
12,Set Me Free,https://books.toscrape.com/catalogue/set-me-fr...,17.46,19
13,Scott Pilgrim's Precious Little Life (Scott Pi...,https://books.toscrape.com/catalogue/scott-pil...,52.29,19
14,Rip it Up and Start Again,https://books.toscrape.com/catalogue/rip-it-up...,35.02,19
15,Our Band Could Be Your Life: Scenes from the A...,https://books.toscrape.com/catalogue/our-band-...,57.25,19
16,Olio,https://books.toscrape.com/catalogue/olio_984/...,23.88,19
17,Mesaerion: The Best Science Fiction Stories 18...,https://books.toscrape.com/catalogue/mesaerion...,37.59,19
18,Libertarianism for Beginners,https://books.toscrape.com/catalogue/libertari...,51.33,19
19,It's Only the Himalayas,https://books.toscrape.com/catalogue/its-only-...,45.17,19
20,In Her Wake,https://books.toscrape.com/catalogue/in-her-wa...,12.84,19
21,How Music Works,https://books.toscrape.com/catalogue/how-music...,37.32,19
22,Foolproof Preserving: A Guide to Small Batch J...,https://books.toscrape.com/catalogue/foolproof...,30.52,19
23,Chase Me (Paris Nights #2),https://books.toscrape.com/catalogue/chase-me-...,25.27,19
24,Black Dust,https://books.toscrape.com/catalogue/black-dus...,34.53,19
25,Birdsong: A Story in Pictures,https://books.toscrape.com/catalogue/birdsong-...,54.64,19
26,America's Cradle of Quarterbacks: Western Penn...,https://books.toscrape.com/catalogue/americas-...,22.50,19
27,Aladdin and His Wonderful Lamp,https://books.toscrape.com/catalogue/aladdin-a...,53.13,19
28,Worlds Elsewhere: Journeys Around Shakespeareâ...,https://books.toscrape.com/catalogue/worlds-el...,40.30,18
29,Wall and Piece,https://books.toscrape.com/catalogue/wall-and-...,44.18,18
30,The Four Agreements: A Practical Guide to Pers...,https://books.toscrape.com/catalogue/the-four-...,17.66,18
31,The Five Love Languages: How to Express Heartf...,https://books.toscrape.com/catalogue/the-five-...,31.05,18
32,The Elephant Tree,https://books.toscrape.com/catalogue/the-eleph...,23.82,18
33,The Bear and the Piano,https://books.toscrape.com/catalogue/the-bear-...,36.89,18
34,Sophie's World,https://books.toscrape.com/catalogue/sophies-w...,15.94,18
35,Penny Maybe,https://books.toscrape.com/catalogue/penny-may...,33.29,18
36,Maude (1883-1993):She Grew Up with the country,https://books.toscrape.com/catalogue/maude-188...,18.02,18
37,"In a Dark, Dark Wood",https://books.toscrape.com/catalogue/in-a-dark...,19.63,18
38,Behind Closed Doors,https://books.toscrape.com/catalogue/behind-cl...,52.22,18
39,You can't bury them all: Poems,https://books.toscrape.com/catalogue/you-cant-...,33.63,17

In [13]:
for detail in books_details:
    print(*detail)

A Light in the Attic https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html 51.77 22
Tipping the Velvet https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html 53.74 20
Soumission https://books.toscrape.com/catalogue/soumission_998/index.html 50.10 20
Sharp Objects https://books.toscrape.com/catalogue/sharp-objects_997/index.html 47.82 20
Sapiens: A Brief History of Humankind https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html 54.23 20
The Requiem Red https://books.toscrape.com/catalogue/the-requiem-red_995/index.html 22.65 19
The Dirty Little Secrets of Getting Your Dream Job https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html 33.34 19
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html 17.93 19
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html 22.60 19
The Black Maria https://books.toscrape.com/catalogue/the-black-maria_991/index.html 52.15 19
Starving Hearts (Triangular Trade Trilogy, #1) https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html 13.99 19
Shakespeare's Sonnets https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html 20.66 19
Set Me Free https://books.toscrape.com/catalogue/set-me-free_988/index.html 17.46 19
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1) https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html 52.29 19
Rip it Up and Start Again https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html 35.02 19
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991 https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html 57.25 19
Olio https://books.toscrape.com/catalogue/olio_984/index.html 23.88 19
Mesaerion: The Best Science Fiction Stories 1800-1849 https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html 37.59 19
Libertarianism for Beginners https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html 51.33 19
It's Only the Himalayas https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html 45.17 19
In Her Wake https://books.toscrape.com/catalogue/in-her-wake_980/index.html 12.84 19
How Music Works https://books.toscrape.com/catalogue/how-music-works_979/index.html 37.32 19
Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More https://books.toscrape.com/catalogue/foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html 30.52 19
Chase Me (Paris Nights #2) https://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html 25.27 19
Black Dust https://books.toscrape.com/catalogue/black-dust_976/index.html 34.53 19
Birdsong: A Story in Pictures https://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html 54.64 19
America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana https://books.toscrape.com/catalogue/americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html 22.50 19
Aladdin and His Wonderful Lamp https://books.toscrape.com/catalogue/aladdin-and-his-wonderful-lamp_973/index.html 53.13 19
Worlds Elsewhere: Journeys Around Shakespeareâs Globe https://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html 40.30 18
Wall and Piece https://books.toscrape.com/catalogue/wall-and-piece_971/index.html 44.18 18
The Four Agreements: A Practical Guide to Personal Freedom https://books.toscrape.com/catalogue/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html 17.66 18
The Five Love Languages: How to Express Heartfelt Commitment to Your Mate https://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html 31.05 18
The Elephant Tree https://books.toscrape.com/catalogue/the-elephant-tree_968/index.html 23.82 18
The Bear and the Piano https://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html 36.89 18
Sophie's World https://books.toscrape.com/catalogue/sophies-world_966/index.html 15.94 18
Penny Maybe https://books.toscrape.com/catalogue/penny-maybe_965/index.html 33.29 18
Maude (1883-1993):She Grew Up with the country https://books.toscrape.com/catalogue/maude-1883-1993she-grew-up-with-the-country_964/index.html 18.02 18
In a Dark, Dark Wood https://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html 19.63 18
Behind Closed Doors https://books.toscrape.com/catalogue/behind-closed-doors_962/index.html 52.22 18
You can't bury them all: Poems https://books.toscrape.com/catalogue/you-cant-bury-them-all-poems_961/index.html 33.63 17

In [20]:
for index, row in df.iterrows():
    for column, value in row.items():
        print(value,end=" ")
    print()

A Light in the Attic https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html 51.77 22
Tipping the Velvet https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html 53.74 20
Soumission https://books.toscrape.com/catalogue/soumission_998/index.html 50.10 20
Sharp Objects https://books.toscrape.com/catalogue/sharp-objects_997/index.html 47.82 20
Sapiens: A Brief History of Humankind https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html 54.23 20
The Requiem Red https://books.toscrape.com/catalogue/the-requiem-red_995/index.html 22.65 19
The Dirty Little Secrets of Getting Your Dream Job https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html 33.34 19
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html 17.93 19
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html 22.60 19
The Black Maria https://books.toscrape.com/catalogue/the-black-maria_991/index.html 52.15 19
Starving Hearts (Triangular Trade Trilogy, #1) https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html 13.99 19
Shakespeare's Sonnets https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html 20.66 19
Set Me Free https://books.toscrape.com/catalogue/set-me-free_988/index.html 17.46 19
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1) https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html 52.29 19
Rip it Up and Start Again https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html 35.02 19
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991 https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html 57.25 19
Olio https://books.toscrape.com/catalogue/olio_984/index.html 23.88 19
Mesaerion: The Best Science Fiction Stories 1800-1849 https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html 37.59 19
Libertarianism for Beginners https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html 51.33 19
It's Only the Himalayas https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html 45.17 19
In Her Wake https://books.toscrape.com/catalogue/in-her-wake_980/index.html 12.84 19
How Music Works https://books.toscrape.com/catalogue/how-music-works_979/index.html 37.32 19
Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More https://books.toscrape.com/catalogue/foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html 30.52 19
Chase Me (Paris Nights #2) https://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html 25.27 19
Black Dust https://books.toscrape.com/catalogue/black-dust_976/index.html 34.53 19
Birdsong: A Story in Pictures https://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html 54.64 19
America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana https://books.toscrape.com/catalogue/americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html 22.50 19
Aladdin and His Wonderful Lamp https://books.toscrape.com/catalogue/aladdin-and-his-wonderful-lamp_973/index.html 53.13 19
Worlds Elsewhere: Journeys Around Shakespeareâs Globe https://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html 40.30 18
Wall and Piece https://books.toscrape.com/catalogue/wall-and-piece_971/index.html 44.18 18
The Four Agreements: A Practical Guide to Personal Freedom https://books.toscrape.com/catalogue/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html 17.66 18
The Five Love Languages: How to Express Heartfelt Commitment to Your Mate https://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html 31.05 18
The Elephant Tree https://books.toscrape.com/catalogue/the-elephant-tree_968/index.html 23.82 18
The Bear and the Piano https://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html 36.89 18
Sophie's World https://books.toscrape.com/catalogue/sophies-world_966/index.html 15.94 18
Penny Maybe https://books.toscrape.com/catalogue/penny-maybe_965/index.html 33.29 18
Maude (1883-1993):She Grew Up with the country https://books.toscrape.com/catalogue/maude-1883-1993she-grew-up-with-the-country_964/index.html 18.02 18
In a Dark, Dark Wood https://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html 19.63 18
Behind Closed Doors https://books.toscrape.com/catalogue/behind-closed-doors_962/index.html 52.22 18
You can't bury them all: Poems https://books.toscrape.com/catalogue/you-cant-bury-them-all-poems_961/index.html 33.63 17

In [9]:
#saving to csv file 
df.to_csv("Bookdetailsfirsttwopages.csv",index=False) #.csv for proper format

In [52]:
#same ans as below but below one worked in codezen 
from bs4 import BeautifulSoup
import pandas as pd
import requests
import re

allPages = ['http://books.toscrape.com/catalogue/page-1.html','http://books.toscrape.com/catalogue/page-2.html']
column_names = ['Title', 'Link', 'Price', 'Quantity in Stock']
base_url = 'http://books.toscrape.com/catalogue/'

allBooks=[]
for i in allPages:
    response = requests.get(i)
    data = BeautifulSoup(response.text, 'html.parser')
    book = data.find_all(class_='product_pod')
    for i in book:
        b_url = base_url + i.h3.a['href']
        allBooks.append(b_url)

        
Book_details=[]
for i in allBooks:
    response = requests.get(i)
    data = BeautifulSoup(response.text, 'html.parser')
    title = data.h1.string
    price = data.find(class_='price_color').string
    qty = data.find(class_='instock availability')
    qty = qty.contents[-1].strip()
    qty = int(re.search('\d+',qty).group())
    price = float(re.search('[\d.]+',price).group())
    Book_details.append([title, i, price, qty])
    
#for i in Book_details:
#print(*i)
df = pd.DataFrame(Book_details,columns=column_names)
for i in range(len(df)):
    print(df['Title'][i],df['Link'][i],df['Price'][i],df['Quantity in Stock'][i])

A Light in the Attic http://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html 51.77 22
Tipping the Velvet http://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html 53.74 20
Soumission http://books.toscrape.com/catalogue/soumission_998/index.html 50.1 20
Sharp Objects http://books.toscrape.com/catalogue/sharp-objects_997/index.html 47.82 20
Sapiens: A Brief History of Humankind http://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html 54.23 20
The Requiem Red http://books.toscrape.com/catalogue/the-requiem-red_995/index.html 22.65 19
The Dirty Little Secrets of Getting Your Dream Job http://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html 33.34 19
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull http://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html 17.93 19
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics http://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html 22.6 19
The Black Maria http://books.toscrape.com/catalogue/the-black-maria_991/index.html 52.15 19
Starving Hearts (Triangular Trade Trilogy, #1) http://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html 13.99 19
Shakespeare's Sonnets http://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html 20.66 19
Set Me Free http://books.toscrape.com/catalogue/set-me-free_988/index.html 17.46 19
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1) http://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html 52.29 19
Rip it Up and Start Again http://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html 35.02 19
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991 http://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html 57.25 19
Olio http://books.toscrape.com/catalogue/olio_984/index.html 23.88 19
Mesaerion: The Best Science Fiction Stories 1800-1849 http://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html 37.59 19
Libertarianism for Beginners http://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html 51.33 19
It's Only the Himalayas http://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html 45.17 19
In Her Wake http://books.toscrape.com/catalogue/in-her-wake_980/index.html 12.84 19
How Music Works http://books.toscrape.com/catalogue/how-music-works_979/index.html 37.32 19
Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More http://books.toscrape.com/catalogue/foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html 30.52 19
Chase Me (Paris Nights #2) http://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html 25.27 19
Black Dust http://books.toscrape.com/catalogue/black-dust_976/index.html 34.53 19
Birdsong: A Story in Pictures http://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html 54.64 19
America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana http://books.toscrape.com/catalogue/americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html 22.5 19
Aladdin and His Wonderful Lamp http://books.toscrape.com/catalogue/aladdin-and-his-wonderful-lamp_973/index.html 53.13 19
Worlds Elsewhere: Journeys Around Shakespeareâs Globe http://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html 40.3 18
Wall and Piece http://books.toscrape.com/catalogue/wall-and-piece_971/index.html 44.18 18
The Four Agreements: A Practical Guide to Personal Freedom http://books.toscrape.com/catalogue/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html 17.66 18
The Five Love Languages: How to Express Heartfelt Commitment to Your Mate http://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html 31.05 18
The Elephant Tree http://books.toscrape.com/catalogue/the-elephant-tree_968/index.html 23.82 18
The Bear and the Piano http://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html 36.89 18
Sophie's World http://books.toscrape.com/catalogue/sophies-world_966/index.html 15.94 18
Penny Maybe http://books.toscrape.com/catalogue/penny-maybe_965/index.html 33.29 18
Maude (1883-1993):She Grew Up with the country http://books.toscrape.com/catalogue/maude-1883-1993she-grew-up-with-the-country_964/index.html 18.02 18
In a Dark, Dark Wood http://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html 19.63 18
Behind Closed Doors http://books.toscrape.com/catalogue/behind-closed-doors_962/index.html 52.22 18
You can't bury them all: Poems http://books.toscrape.com/catalogue/you-cant-bury-them-all-poems_961/index.html 33.63 17

ASSIGNMENT

Print the data of first 3 movies


From this link: https://www.imdb.com/search/title/?release_date=2018&sort=num_votes,desc&page=1&ref_=adv_nxt
Find and print the name and genre of the first 3 titles
Output Format :
title_name_1 ; genre1_1, genre1_2 ..
title_name_2 ; genre2_1, genre2_2 ..
title_name_2 ; genre3_1, genre3_2 ..

In [54]:
import requests 
from bs4 import BeautifulSoup as soup 

response=requests.get('https://www.imdb.com/search/title/?release_date=2018&sort=num_votes,desc&page=1&ref_=adv_nxt')
data=soup(response.text,'html.parser')
data

<!DOCTYPE html>

<html xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#">
<head>
<meta charset="utf-8"/>
<script type="text/javascript">var IMDbTimer={starttime: new Date().getTime(),pt:'java'};</script>
<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadTitle", {wb: 1});
    }
</script>
<script>(function(t){ (t.events = t.events || {})["csm_head_pre_title"] = new Date().getTime(); })(IMDbTimer);</script>
<title>Released between 2018-01-01 and 2018-12-31
(Sorted by Number of Votes Descending) - IMDb</title>
<script>(function(t){ (t.events = t.events || {})["csm_head_post_title"] = new Date().getTime(); })(IMDbTimer);</script>
<script>
    if (typeof uet == 'function') {
      uet("be", "LoadTitle", {wb: 1});
    }
</script>
<script>
    if (typeof uex == 'function') {
      uex("ld", "LoadTitle", {wb: 1});
    }
</script>
<link href="https://www.imdb.com/search/title/?release_date=2018-01-01,2018-12-31" rel="canonical"/>
<meta content="http://www.imdb.com/search/title/?release_date=2018-01-01,2018-12-31" property="og:url">
<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadIcons", {wb: 1});
    }
</script>
<script>(function(t){ (t.events = t.events || {})["csm_head_pre_icon"] = new Date().getTime(); })(IMDbTimer);</script>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/favicon_desktop_32x32._CB1582158068_.png" rel="icon" sizes="32x32"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/favicon_iPad_retina_167x167._CB1582158068_.png" rel="icon" sizes="167x167"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/favicon_iPhone_retina_180x180._CB1582158069_.png" rel="icon" sizes="180x180"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/apple-touch-icon-mobile._CB479963088_.png" rel="apple-touch-icon"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/apple-touch-icon-mobile-76x76._CB479962152_.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/apple-touch-icon-mobile-120x120._CB479963088_.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/apple-touch-icon-web-152x152._CB479963088_.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/android-mobile-196x196._CB479962153_.png" rel="shortcut icon" sizes="196x196"/>
<meta content="#000000" name="theme-color"/>
<link href="https://m.media-amazon.com/images/S/sash/MzfIBMq9GBucYqW.xml" rel="search" title="IMDb" type="application/opensearchdescription+xml"/>
<script>(function(t){ (t.events = t.events || {})["csm_head_post_icon"] = new Date().getTime(); })(IMDbTimer);</script>
<script>
    if (typeof uet == 'function') {
      uet("be", "LoadIcons", {wb: 1});
    }
</script>
<script>
    if (typeof uex == 'function') {
      uex("ld", "LoadIcons", {wb: 1});
    }
</script>
<meta content="advsearch" property="pageType"/>
<meta content="title" property="subpageType"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images/social/imdb_logo._CB410901634_.png" rel="image_src"/>
<meta content="https://m.media-amazon.com/images/G/01/imdb/images/social/imdb_logo._CB410901634_.png" property="og:image"/>
<meta content="115109575169727" property="fb:app_id"/>
<meta content="Released between 2018-01-01 and 2018-12-31
(Sorted by Number of Votes Descending) - IMDb" property="og:title"/>
<meta content="IMDb" property="og:site_name"/>
<meta content="Released between 2018-01-01 and 2018-12-31
(Sorted by Number of Votes Descending) - IMDb" name="title"/>
<meta content="IMDb's advanced search allows you to run extremely powerful queries over all people and titles in the database. Find exactly what you're looking for!" name="description"/>
<meta content="IMDb's advanced search allows you to run extremely powerful queries over all people and titles in the database. Find exactly what you're looking for!" property="og:description"/>
<meta content="ERVHBH2B2808ZV9V1M9W" name="request_id"/>
<script>
        (function (win) {
            win.PLAID_LOAD_FONTS_FIRED = true;

            if (typeof win.FontFace !== "undefined"
                && typeof win.Promise !== "undefined") {
                if (win.ue) {
                    win.uet("bb", "LoadRoboto", { wb: 1 });
                }
                var allowableLoadTime = 1000;
                var startTimeInt = +new Date();
                var roboto = new FontFace('Roboto',
                    'url(https://m.media-amazon.com/images/G/01/IMDb/cm9ib3Rv.woff2)',
                    { style:'normal', weight: 400 });
                var robotoMedium = new FontFace('Roboto',
                    'url(https://m.media-amazon.com/images/G/01/IMDb/cm9ib3RvTWVk.woff2)',
                    { style:'normal', weight: 500 });
                var robotoBold = new FontFace('Roboto',
                    'url(https://m.media-amazon.com/images/G/01/IMDb/cm9ib3RvQm9sZA.woff2)',
                    { style:'normal', weight: 600 });
                var robotoLoaded = roboto.load();
                var robotoMediumLoaded = robotoMedium.load();
                var robotoBoldLoaded = robotoBold.load();

                win.Promise.all([robotoLoaded, robotoMediumLoaded, robotoBoldLoaded]).then(function() {
                    var loadTimeInt = +new Date();
                    var robotoLoadedCount = 0;
                    if ((loadTimeInt - startTimeInt) <= allowableLoadTime) {
                        win.document.fonts.add(roboto);
                        win.document.fonts.add(robotoMedium);
                        win.document.fonts.add(robotoBold);
                        robotoLoadedCount++;
                    }
                    if (win.ue) {
                        win.ue.count("roboto-loaded", robotoLoadedCount);
                        win.uet("be", "LoadRoboto", { wb: 1 });
                        win.uex("ld", "LoadRoboto", { wb: 1 });
                    }
                }).catch(function() {
                    if (win.ue) {
                        win.ue.count("roboto-loaded", 0);
                    }
                });
            } else {
                if (win.ue) {
                    win.ue.count("roboto-load-not-attempted", 1);
                }
            }
        })(window);
    </script>
<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadCSS", {wb: 1});
    }
</script>
<script>(function(t){ (t.events = t.events || {})["csm_head_pre_css"] = new Date().getTime(); })(IMDbTimer);</script>
<link href="https://m.media-amazon.com/images/S/sash/5OFdYY5jIjYtZ2o.css" rel="stylesheet" type="text/css">
<!-- h=ics-c52xl-4-1a-796afec2.us-east-1 -->
<!--[if IE]><link rel="stylesheet" type="text/css" href="https://m.media-amazon.com/images/S/sash/pXHSPBTKPo0GIjW.css" /><![endif]-->
<link href="https://m.media-amazon.com/images/S/sash/vEv7EhTS45PyD8e.css" rel="stylesheet" type="text/css"/>
<link href="https://m.media-amazon.com/images/S/sash/i-Y65BmJrKWIfbK.css" rel="stylesheet" type="text/css"/>
<link href="https://m.media-amazon.com/images/S/sash/HqcrRlviNTScutU.css" rel="stylesheet" type="text/css"/>
<link href="https://m.media-amazon.com/images/S/sash/mrwUCCyp3V14GU0.css" rel="stylesheet" type="text/css"/>
<link href="https://m.media-amazon.com/images/S/sash/sHfJ8wTsDnFAHcY.css" rel="stylesheet" type="text/css"/>
<link href="https://m.media-amazon.com/images/S/sash/4w4OQGgDeMIrb8f.css" rel="stylesheet" type="text/css"/>
<noscript>
<link href="https://m.media-amazon.com/images/S/sash/CCc6Ja$8QUPPKkY.css" rel="stylesheet" type="text/css"/>
</noscript>
<script>(function(t){ (t.events = t.events || {})["csm_head_post_css"] = new Date().getTime(); })(IMDbTimer);</script>
<script>
    if (typeof uet == 'function') {
      uet("be", "LoadCSS", {wb: 1});
    }
</script>
<script>
    if (typeof uex == 'function') {
      uex("ld", "LoadCSS", {wb: 1});
    }
</script>
<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadJS", {wb: 1});
    }
</script>
<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadHeaderJS", {wb: 1});
    }
</script>
<script>(function(t){ (t.events = t.events || {})["csm_head_pre_ads"] = new Date().getTime(); })(IMDbTimer);</script>
<script type="text/javascript">
            // ensures js doesn't die if ads service fails.
            // Note that we need to define the js here, since ad js is being rendered inline after this.
            (function(f) {
                // Fallback javascript, when the ad Service call fails.

                if((window.csm == null || window.generic == null || window.consoleLog == null)) {
                    if (window.console && console.log) {
                        console.log("one or more of window.csm, window.generic or window.consoleLog has been stubbed...");
                    }
                }

                window.csm = window.csm || { measure:f, record:f, duration:f, listen:f, metrics:{} };
                window.generic = window.generic || { monitoring: { start_timing: f, stop_timing: f } };
                window.consoleLog = window.consoleLog || f;
            })(function() {});
        </script>
<script type="text/javascript">window.useRatingTaskCompletion = true;</script>
<script>
    if ('csm' in window) {
      csm.measure('csm_head_delivery_finished');
    }
  </script>
<script>
    if (typeof uet == 'function') {
      uet("be", "LoadHeaderJS", {wb: 1});
    }
</script>
<script>
    if (typeof uex == 'function') {
      uex("ld", "LoadHeaderJS", {wb: 1});
    }
</script>
<script>
    if (typeof uet == 'function') {
      uet("be", "LoadJS", {wb: 1});
    }
</script>
<script>
    if (typeof uex == 'function') {
      uex("ld", "LoadJS", {wb: 1});
    }
</script>
</link></meta></head>
<body class="fixed" id="styleguide-v2">
<script>
    if (typeof uet == 'function') {
      uet("bb");
    }
</script>
<script>
    if ('csm' in window) {
      csm.measure('csm_body_delivery_started');
    }
  </script>
<script>
    if (typeof uet == 'function') {
      uet("ns");
    }
</script>
<style data-styled="true" data-styled-version="5.3.5">.hKcFfj{-webkit-flex-shrink:0;-ms-flex-negative:0;flex-shrink:0;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:center;-webkit-justify-content:center;-ms-flex-pack:center;justify-content:center;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;margin-left:0.25rem;margin-right:auto;-webkit-order:1;-ms-flex-order:1;order:1;position:relative;}/*!sc*/
@media screen and (min-width:1024px){.hKcFfj{margin-left:auto;margin-right:0.5rem;-webkit-order:0;-ms-flex-order:0;order:0;padding-left:0;}}/*!sc*/
@media (hover:hover) and (pointer:fine){.hKcFfj:focus{outline:1px dashed currentColor;}.hKcFfj:focus:active{outline:0;}.hKcFfj:before,.hKcFfj:after{border-radius:10%;bottom:0;content:'';height:100%;left:0;margin:auto;opacity:0;position:absolute;right:0;top:0;-webkit-transition:opacity 0.2s cubic-bezier(1,1,1,1);transition:opacity 0.2s cubic-bezier(1,1,1,1);width:100%;background:rgb(0,0,0);background:var(--ipt-on-accent1-color,rgb(0,0,0));}.hKcFfj:hover:before{opacity:0.08;opacity:var(--ipt-base-hover-opacity,0.08);}.hKcFfj:active:after{opacity:0.16;opacity:var(--ipt-base-pressed-opacity,0.16);}}/*!sc*/
data-styled.g1[id="sc-bczRLJ"]{content:"hKcFfj,"}/*!sc*/
.fwtMQY{background:rgb(31,31,31);background:var(--ipt-baseAlt-shade1-bg,rgb(31,31,31));width:100%;left:0;right:0;top:100%;position:absolute;}/*!sc*/
@media screen and (min-width:600px){.fwtMQY{border-radius:.25rem;border-radius:var(--ipt-cornerRadius,.25rem);top:calc(100% + 0.25rem);}}/*!sc*/
.fwtMQY ul{margin:0;padding:0;list-style:none;}/*!sc*/
.fwtMQY ul li{display:inline;}/*!sc*/
.fwtMQY .anim-enter{opacity:0;}/*!sc*/
.fwtMQY .anim-enter-active{opacity:1;-webkit-transition:opacity 200ms;transition:opacity 200ms;}/*!sc*/
.fwtMQY .anim-exit{opacity:1;}/*!sc*/
.fwtMQY .anim-exit-active{opacity:0;-webkit-transition:opacity 200ms;transition:opacity 200ms;}/*!sc*/
data-styled.g2[id="sc-gsnTZi"]{content:"fwtMQY,"}/*!sc*/
.lbYfkb li:first-child > .searchResult{border-top:none;}/*!sc*/
.lbYfkb .searchTypeahead__input{font-family:'Roboto','Helvetica','Arial',sans-serif;font-family:var(--ipt-font-family);font-size:1rem;font-size:var(--ipt-type-body-size,1rem);font-weight:400;font-weight:var(--ipt-type-body-weight,400);-webkit-letter-spacing:.03125em;-moz-letter-spacing:.03125em;-ms-letter-spacing:.03125em;letter-spacing:.03125em;-webkit-letter-spacing:var(--ipt-type-body-letterSpacing,.03125em);-moz-letter-spacing:var(--ipt-type-body-letterSpacing,.03125em);-ms-letter-spacing:var(--ipt-type-body-letterSpacing,.03125em);letter-spacing:var(--ipt-type-body-letterSpacing,.03125em);line-height:1.5rem;line-height:var(--ipt-type-body-lineHeight,1.5rem);text-transform:none;text-transform:var(--ipt-type-body-textTransform,none);color:rgb(255,255,255);color:var(--ipt-on-baseAlt-color,rgb(255,255,255));caret-color:rgb(255,255,255);caret-color:var(--ipt-on-baseAlt-color,rgb(255,255,255));}/*!sc*/
.lbYfkb .searchTypeahead__input:placeholder{color:rgba(255,255,255,0.5);color:var(--ipt-on-baseAlt-textHint-color,rgba(255,255,255,0.5));}/*!sc*/
@media screen and (min-width:600px){.lbYfkb .searchTypeahead__input{font-family:'Roboto','Helvetica','Arial',sans-serif;font-family:var(--ipt-font-family);font-size:.875rem;font-size:var(--ipt-type-bodySmall-size,.875rem);font-weight:400;font-weight:var(--ipt-type-bodySmall-weight,400);-webkit-letter-spacing:.01786em;-moz-letter-spacing:.01786em;-ms-letter-spacing:.01786em;letter-spacing:.01786em;-webkit-letter-spacing:var(--ipt-type-bodySmall-letterSpacing,.01786em);-moz-letter-spacing:var(--ipt-type-bodySmall-letterSpacing,.01786em);-ms-letter-spacing:var(--ipt-type-bodySmall-letterSpacing,.01786em);letter-spacing:var(--ipt-type-bodySmall-letterSpacing,.01786em);line-height:1.25rem;line-height:var(--ipt-type-bodySmall-lineHeight,1.25rem);text-transform:none;text-transform:var(--ipt-type-bodySmall-textTransform,none);color:rgba(0,0,0,0.87);color:var(--ipt-on-base-textPrimary-color,rgba(0,0,0,0.87));caret-color:rgba(0,0,0,0.54);caret-color:var(--ipt-on-base-textSecondary-color,rgba(0,0,0,0.54));}}/*!sc*/
data-styled.g7[id="sc-gKXOVf"]{content:"lbYfkb,"}/*!sc*/
.iMMgxe{position:relative;}/*!sc*/
.iMMgxe.navbar__flyout__text-button-after-mobile,.iMMgxe .navbar__flyout__text-button-after-mobile{display:none;}/*!sc*/
.iMMgxe .navbar__flyout__text-button-after-mobile > div{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;}/*!sc*/
.iMMgxe .navbar__flyout--menu{top:100%;position:absolute;margin-top:0.25rem;}/*!sc*/
.iMMgxe.iMMgxe.navbar__flyout--positionLeft .navbar__flyout--menu{left:0;right:auto;}/*!sc*/
@media screen and (min-width:600px){.iMMgxe.navbar__flyout--breakpoint-m .navbar__flyout__icon-on-mobile{display:none;}.iMMgxe.navbar__flyout--breakpoint-m .navbar__flyout__text-button-after-mobile{display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;}}/*!sc*/
@media screen and (min-width:1024px){.iMMgxe.navbar__flyout--breakpoint-l .navbar__flyout__icon-on-mobile{display:none;}.iMMgxe.navbar__flyout--breakpoint-l .navbar__flyout__text-button-after-mobile{display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;}}/*!sc*/
@media screen and (min-width:1280px){.iMMgxe.navbar__flyout--breakpoint-xl .navbar__flyout__icon-on-mobile{display:none;}.iMMgxe.navbar__flyout--breakpoint-xl .navbar__flyout__text-button-after-mobile{display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;}}/*!sc*/
.iMMgxe .navbar__flyout__text-button-post-icon{-webkit-transition:-webkit-transform 0.2s;-webkit-transition:transform 0.2s;transition:transform 0.2s;-webkit-transform:rotateX(0);-ms-transform:rotateX(0);transform:rotateX(0);}/*!sc*/
.iMMgxe.navbar__flyout--isVisible .navbar__flyout__text-button-post-icon{-webkit-transform:rotateX(180deg);-ms-transform:rotateX(180deg);transform:rotateX(180deg);}/*!sc*/
data-styled.g8[id="sc-iBkjds"]{content:"iMMgxe,"}/*!sc*/
.ifbTmq .searchCatSelector__opener{border-radius:2px 0 0 2px;padding:0 0.25rem 0 0.75rem;min-height:32px;height:20px;border-right:1px solid rgba(0,0,0,0.3);}/*!sc*/
.ifbTmq .searchCatSelector__opener svg{margin:0;}/*!sc*/
.ifbTmq .searchCatSelector .searchCatSelector__item{-webkit-transition:color 0.15s;transition:color 0.15s;cursor:poiner;}/*!sc*/
.ifbTmq .searchCatSelector .searchCatSelector__item .searchCatSelector__itemIcon{margin-right:0.75rem;opacity:0.5;-webkit-transition:opacity 0.2s;transition:opacity 0.2s;}/*!sc*/
.ifbTmq .searchCatSelector .searchCatSelector__item:hover .searchCatSelector__itemIcon,.ifbTmq .searchCatSelector .searchCatSelector__item:focus .searchCatSelector__itemIcon,.ifbTmq .searchCatSelector .searchCatSelector__item.searchCatSelector__itemSelected .searchCatSelector__itemIcon{opacity:1;}/*!sc*/
.ifbTmq .searchCatSelector .searchCatSelector__item.searchCatSelector__itemSelected{color:rgb(245,197,24);color:var(--ipt-on-base-accent1-color,rgb(245,197,24));}/*!sc*/
data-styled.g9[id="sc-ftvSup"]{content:"ifbTmq,"}/*!sc*/
.exojnx{background:rgb(31,31,31);background:var(--ipt-baseAlt-shade1-bg,rgb(31,31,31));display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-flex:1;-webkit-flex-grow:1;-ms-flex-positive:1;flex-grow:1;margin:0;padding:0;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;}/*!sc*/
@media screen and (min-width:600px){.exojnx.searchform--focused .searchform__submit{background:transparent;opacity:1;}}/*!sc*/
@media screen and (min-width:600px){.exojnx{-webkit-transition:border 0.2s,background-color 0.2s,box-shadow 0.2s;transition:border 0.2s,background-color 0.2s,box-shadow 0.2s;background:rgb(255,255,255);background:var(--ipt-base-bg,rgb(255,255,255));border-radius:.25rem;border-radius:var(--ipt-cornerRadius,.25rem);}.exojnx.searchform--focused{background:rgb(255,255,255);background:var(--ipt-base-bg,rgb(255,255,255));outline:none;border-color:none;box-shadow:inset 0 0 0 2px rgb(245,197,24);box-shadow:inset 0 0 0 2px var(--ipt-accent1-color,rgb(245,197,24));}}/*!sc*/
.exojnx .searchform__inputContainer{width:100%;padding-right:3.5rem;}/*!sc*/
.exojnx .searchform__submit{background:rgb(250,250,250);background:var(--ipt-base-shade1-bg,rgb(250,250,250));color:rgba(0,0,0,0.54);color:var(--ipt-on-base-textSecondary-color,rgba(0,0,0,0.54));border-radius:.25rem;border-radius:var(--ipt-cornerRadius,.25rem);position:absolute;right:0.35rem;min-width:2rem;cursor:pointer;top:0.35rem;-webkit-transition:all 0.2s;transition:all 0.2s;}/*!sc*/
@media screen and (min-width:600px){.exojnx .searchform__submit{background:rgb(255,255,255);background:var(--ipt-base-bg,rgb(255,255,255));}}/*!sc*/
.exojnx .imdb-header-search__input{background:transparent;-webkit-box-flex:1;-webkit-flex-grow:1;-ms-flex-positive:1;flex-grow:1;outline:none;padding:1rem 1rem 1rem 0.75rem;width:100%;}/*!sc*/
@media screen and (min-width:600px){.exojnx .imdb-header-search__input{padding:0.375em 0 0.375rem 0.5rem;}}/*!sc*/
.exojnx .imdb-header-search__input::-ms-clear{display:none;}/*!sc*/
data-styled.g10[id="sc-papXJ"]{content:"exojnx,"}/*!sc*/

In [55]:
count=0
liname=data.find_all(class_="lister-item-header")
ligenre=data.find_all(class_='genre')
d={}
for i in liname :
    if count==3:
        break 
    d[liname[count].a.text]=list(ligenre[count].stripped_strings)[0]  #to get name 
#     print(li[count].a.text)
    count+=1
# print(d)

for key,value in d.items():
    print(key,";",value)

Avengers: Infinity War ; Action, Adventure, Sci-Fi
Black Panther ; Action, Adventure, Sci-Fi
Spider-Man: Into the Spider-Verse ; Animation, Action, Adventure

In [56]:
ligenre=data.find_all(class_='genre')  #to get genre as used abve 
list(ligenre[0].stripped_strings)[0]

'Action, Adventure, Sci-Fi'

titles with most votes

Print the names of movies with highest number of votes from year 2010 to 2014
Note : Print the titles line wise starting from year 2010
Output Format :
title_name_1
title_name_2
title_name_3
.
Link:https://www.imdb.com/search/title/?release_date=2018&sort=num_votes,desc&page=1&ref_=adv_nxt

In [ ]:

#called link has already filtered as per number of votes 

response=requests.get('https://www.imdb.com/search/title/?release_date=2018&sort=num_votes,desc&page=1&ref_=adv_nxt')
data=soup(response.text,'html.parser')

#as you can see in the url release data =2018 we need to update the url as per our requirement so : 
#first firlter using release date you will get this link :https://www.imdb.com/search/title/?release_date=2018-01-01,2018-12-31&sort=release_date,desc
#now update the link as per your date

In [70]:
import requests
from bs4 import BeautifulSoup as soup

# Define the URL for IMDb's advanced search for movies released between 2010 and 2014, sorted by number of votes.
# base_url = "https://www.imdb.com/search/title/?release_date=2010-01-01,2014-12-31&sort=num_votes,desc&page="
#but note we only need top rated movie from each year so we can first visit filters for each ear and update based on number 
#of votes 
years=["2010","2011","2012","2013","2014"]
base_url="https://www.imdb.com/search/title/?"
for i in years:
    restofurl="release_date="+i+"&sort=num_votes,desc&page=1&ref_=adv_nxt"
    response=requests.get(base_url+restofurl)
    data=soup(response.text,'html.parser')
    ans=data.find_all(class_="lister-item-header")[0].a.text
    print(ans)

Inception
Game of Thrones
The Dark Knight Rises
The Wolf of Wall Street
Interstellar

title with maximum duration

Out of the first 250 titles with highest number of votes in 2018,find which title has the maximum duration.
Output Format :
title_name title_duration

link:https://www.imdb.com/search/title/?release_date=2018&sort=num_votes,desc&page=1&ref_=adv_nxt

In [78]:
#each page has 50 so total page we need to call = 5, 5x50=250 for highest number of votes 
#then see maximum duration 
#first to get the runtime 

data.find_all(class_="runtime")[0].string
#need to convert it to int to compare properly

'169 min'

In [88]:
#step calling all pages and comparing the runtime, keep the title which has max 

import requests 
from bs4 import BeautifulSoup as soup
import re 

base_url="https://www.imdb.com/"
current_page="search/title/?release_date=2018-01-01,2018-12-31&sort=num_votes,desc"
next_page_url=data.find(class_="lister-page-next next-page")["href"]
title=""
duration=0
for i in range(5):
    response=requests.get(base_url+current_page)
    data=soup(response.text,"html.parser")
    for j in range(50):
        runtime=data.find_all(class_="runtime")[j].string
        runtime=int(re.search('\d+',runtime).group())
        if runtime>duration:
            duration=runtime 
            runtime=0 
            title=data.find_all(class_="lister-item-header")[j].a.text #store the title as well if runtime is max 
print(title,duration)

The Haunting of Hill House 572

Image with maximum area

From this website :
Find and print the src of the img tag which occupies the maximum area on the page.
Note :
Ignore images which doesn't have height or width attributes
Output Format :
src_of_image

link:https://en.wikipedia.org/wiki/Artificial_intelligence

In [104]:

import requests 
from bs4 import BeautifulSoup as soup 
import re 

response=requests.get("https://en.wikipedia.org/wiki/Artificial_intelligence")
data=soup(response.text,"html.parser")
#first we can load all img tags 
maxarea=0
maxsrc=""
image_list=data.find_all('img')
for i in range(len(image_list)):
    if "height" in  image_list[i].attrs and "width" in  image_list[i].attrs :  #only if attrs has height and width 
        #to find area height Xwidth 
        area=int(image_list[i]["height"]) * int(image_list[i]["width"])
        if area>maxarea:
            maxarea=area
            maxsrc=image_list[i]["src"]
print(maxsrc)

//upload.wikimedia.org/wikipedia/commons/thumb/1/13/Joseph_Ayerle_portrait_of_Ornella_Muti_%28detail%29%2C_calculated_by_Artificial_Intelligence_%28AI%29_technology.jpg/220px-Joseph_Ayerle_portrait_of_Ornella_Muti_%28detail%29%2C_calculated_by_Artificial_Intelligence_%28AI%29_technology.jpg

Quotes with tag humor

Find all the quotes that have the tag as "humor" from this website
Output Format :
quote1
quote2
quote3
.
.
.

link:https://quotes.toscrape.com/

In [137]:
#to find tag
data.find_all(class_="tag")  #but this will not be parallel to count of quote since one quote has multiple tags so 
data.find_all(class_="keywords") #it has tags in content value !!
a=data.find_all(class_="keywords")[5]["content"]
#to get seperate string values
a.split(",")

['adulthood', 'success', 'value']

In [142]:
re.search("value",a).group() # to find the given

'value'

In [115]:
#to find quote 
data.find_all(class_="text")

[<span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>,
 <span class="text" itemprop="text">“It is our choices, Harry, that show what we truly are, far more than our abilities.”</span>,
 <span class="text" itemprop="text">“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”</span>,
 <span class="text" itemprop="text">“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”</span>,
 <span class="text" itemprop="text">“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”</span>,
 <span class="text" itemprop="text">“Try not to become a man of success. Rather become a man of value.”</span>,
 <span class="text" itemprop="text">“It is better to be hated for what you are than to be loved for what you are not.”</span>,
 <span class="text" itemprop="text">“I have not failed. I've just found 10,000 ways that won't work.”</span>,
 <span class="text" itemprop="text">“A woman is like a tea bag; you never know how strong it is until it's in hot water.”</span>,
 <span class="text" itemprop="text">“A day without sunshine is like, you know, night.”</span>]

In [146]:
import requests 
import re
from bs4 import BeautifulSoup as soup 

response=requests.get("https://quotes.toscrape.com/")
data=soup(response.text,"html.parser")
#so now to get all tags named humor
quotelist=data.find_all(class_="text")
for i in range(len(quotelist)):
    keyword=data.find_all(class_="keywords")[i]["content"]
    if re.search("humor",keyword) is not None:
        print(data.find_all(class_="text")[i].string)
        
        
#but this is only for one page 
#all te quotes are asked so need to loop over all the availale pages 
#one more thing we can do is filter humor in link itself:https://quotes.toscrape.com/tag/humor/

“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
“A day without sunshine is like, you know, night.”

In [ ]:
import requests 
import re
from bs4 import BeautifulSoup as soup 

base_url="https://quotes.toscrape.com/tag/humor/"
response=requests.get(base_url)
i=1
while response.status_code==200:  #this won't work as all other pages are still loading no 404 error so just do it twice 
    
    current_page="page/"+str(i)+"/"
    response=requests.get(base_url+current_page)
    i=i+1
    data=soup(response.text,'html.parser')
    quotelist=data.find_all(class_="text")
    for i in range(len(quotelist)):
        print(data.find_all(class_="text")[i].string)

“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
“A day without sunshine is like, you know, night.”
“Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car.”
“Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.”
“All you need is love. But a little chocolate now and then doesn't hurt.”
“Remember, we're madly in love, so it's all right to kiss me anytime you feel like it.”
“Some people never go crazy. What truly horrible lives they must lead.”
“The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.”
“Think left and think right and think low and think high. Oh, the thinks you can think up if only you try!”
“The reason I talk to myself is because I’m the only one whose answers I accept.”

In [3]:
import requests 
import re
from bs4 import BeautifulSoup as soup 

base_url="https://quotes.toscrape.com/tag/humor/"
response=requests.get(base_url)
i=1
while i<3: 
    
    current_page="page/"+str(i)+"/"
    response=requests.get(base_url+current_page)
    i=i+1
    data=soup(response.text,'html.parser')
    quotelist=data.find_all(class_="text")
    for k in range(len(quotelist)):
        print(data.find_all(class_="text")[k].string)

“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
“A day without sunshine is like, you know, night.”
“Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car.”
“Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.”
“All you need is love. But a little chocolate now and then doesn't hurt.”
“Remember, we're madly in love, so it's all right to kiss me anytime you feel like it.”
“Some people never go crazy. What truly horrible lives they must lead.”
“The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.”
“Think left and think right and think low and think high. Oh, the thinks you can think up if only you try!”
“The reason I talk to myself is because I’m the only one whose answers I accept.”
“I am free of all prejudice. I hate everyone equally. ”
“A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.”

Print all authors

Find and print the names of all the different authors from all pages of this website
Note : Print the names of all authors line wise sorted in dictionary order
Output Format :
author1
author2
author3
.
.
.
link:https://quotes.toscrape.com/

In [19]:
import requests
from bs4 import BeautifulSoup as soup 

dauthors={}
base_url="https://quotes.toscrape.com/"
#for fist page or homepage
response=requests.get(base_url)
data=soup(response.text,'html.parser')
#to find authors
for a in range(len(data.find_all(class_="quote"))):
    author=data.find_all(class_="quote")[a].find(class_="author").string
    #add it to dict to keep unique keys only 
    dauthors[author]=dauthors.get(author,0)


next_page=data.find(class_="next").a["href"]
#need to stop as soon as next button stops being visible so 
while next_page is not None:
    next_page_url=base_url+data.find(class_="next").a["href"]
    response=requests.get(next_page_url)
    data=soup(response.text,'html.parser')
    for a in range(len(data.find_all(class_="quote"))):
        author=data.find_all(class_="quote")[a].find(class_="author").string
        #add it to dict to keep unique keys only 
        dauthors[author]=dauthors.get(author,0)
    next_page=data.find(class_="next")

    
#need to sort in dict name 

sorted_keys = sorted(dauthors.keys())
for i in sorted_keys:
    print(i)

Albert Einstein
Alexandre Dumas fils
Alfred Tennyson
Allen Saunders
André Gide
Ayn Rand
Bob Marley
C.S. Lewis
Charles Bukowski
Charles M. Schulz
Douglas Adams
Dr. Seuss
E.E. Cummings
Eleanor Roosevelt
Elie Wiesel
Ernest Hemingway
Friedrich Nietzsche
Garrison Keillor
George Bernard Shaw
George Carlin
George Eliot
George R.R. Martin
Harper Lee
Haruki Murakami
Helen Keller
J.D. Salinger
J.K. Rowling
J.M. Barrie
J.R.R. Tolkien
James Baldwin
Jane Austen
Jim Henson
Jimi Hendrix
John Lennon
Jorge Luis Borges
Khaled Hosseini
Madeleine L'Engle
Marilyn Monroe
Mark Twain
Martin Luther King Jr.
Mother Teresa
Pablo Neruda
Ralph Waldo Emerson
Stephenie Meyer
Steve Martin
Suzanne Collins
Terry Pratchett
Thomas A. Edison
W.C. Fields
William Nicholson

Birth Date of authors

Find the birth date of authors whose name start with 'J' from this website
Note : Print a dictionary containing the name as key and the birth date as value.The Names of authors should be alphabetically sorted.
Output Format :
{'author_1': 'month day, year', 'author_2': 'month day, year', ....}

link:https://quotes.toscrape.com/

In [20]:
#need to first check if name start with a then go to their about page to extract the birth date 
#to get author birth date
link="https://quotes.toscrape.com/author/"+"Albert-Einstein/"
response=requests.get(link)
data=soup(response.text,'html.parser')
data.find(class_="author-born-date").string

'March 14, 1879'

In [22]:
s="abjbj"
s.lower().startswith('a')  #using this string function to find start with j

True

In [71]:
#full code 
import requests 
from bs4 import BeautifulSoup as soup 


author_details={}
base_url="https://quotes.toscrape.com/"
#for fist page or homepage
response=requests.get(base_url)
data=soup(response.text,'html.parser')
#to find authors
for a in range(len(data.find_all(class_="quote"))):
    author=data.find_all(class_="quote")[a].find(class_="author").string
    if author.lower().startswith('j'):
        ref_url=data.find_all(class_="quote")[a].a["href"]
        about_url= base_url+ref_url
        responseabout=requests.get(about_url)
        databout=soup(responseabout.text,'html.parser')
        date=databout.find(class_="author-born-date").string
        author_details[author]=date
        print(about_url)
        print(author,date)
        
#for other pages 

    
next_page=data.find(class_="next").a["href"]
#need to stop as soon as next button stops being visible so 
while next_page is not None:
    next_page_url=base_url+data.find(class_="next").a["href"]
    response=requests.get(next_page_url)
    data=soup(response.text,'html.parser')
    for a in range(len(data.find_all(class_="quote"))):
        author=data.find_all(class_="quote")[a].find(class_="author").string
        if author.lower().startswith('j'):
            ref_url=data.find_all(class_="quote")[a].a["href"]
            about_url= base_url+ref_url
            responseabout=requests.get(about_url)
            databout=soup(responseabout.text,'html.parser')
            date=databout.find(class_="author-born-date").string
           
            author_details[author]=date
            print(about_url)
            print(author,date)

    next_page=data.find(class_="next")


author_details

https://quotes.toscrape.com//author/J-K-Rowling
J.K. Rowling July 31, 1965
https://quotes.toscrape.com//author/Jane-Austen
Jane Austen December 16, 1775
https://quotes.toscrape.com//author/J-K-Rowling
J.K. Rowling July 31, 1965
https://quotes.toscrape.com//author/Jim-Henson
Jim Henson September 24, 1936
https://quotes.toscrape.com//author/J-K-Rowling
J.K. Rowling July 31, 1965
https://quotes.toscrape.com//author/J-K-Rowling
J.K. Rowling July 31, 1965
https://quotes.toscrape.com//author/J-K-Rowling
J.K. Rowling July 31, 1965
https://quotes.toscrape.com//author/Jorge-Luis-Borges
Jorge Luis Borges August 24, 1899
https://quotes.toscrape.com//author/J-K-Rowling
J.K. Rowling July 31, 1965
https://quotes.toscrape.com//author/James-Baldwin
James Baldwin August 02, 1924
https://quotes.toscrape.com//author/Jane-Austen
Jane Austen December 16, 1775
https://quotes.toscrape.com//author/J-R-R-Tolkien
J.R.R. Tolkien January 03, 1892
https://quotes.toscrape.com//author/J-K-Rowling
J.K. Rowling July 31, 1965
https://quotes.toscrape.com//author/J-D-Salinger
J.D. Salinger January 01, 1919
https://quotes.toscrape.com//author/John-Lennon
John Lennon October 09, 1940
https://quotes.toscrape.com//author/Jane-Austen
Jane Austen December 16, 1775
https://quotes.toscrape.com//author/J-K-Rowling
J.K. Rowling July 31, 1965
https://quotes.toscrape.com//author/Jane-Austen
Jane Austen December 16, 1775
https://quotes.toscrape.com//author/Jane-Austen
Jane Austen December 16, 1775
https://quotes.toscrape.com//author/J-K-Rowling
J.K. Rowling July 31, 1965
https://quotes.toscrape.com//author/Jimi-Hendrix
Jimi Hendrix November 27, 1942
https://quotes.toscrape.com//author/J-M-Barrie
J.M. Barrie May 09, 1860

{'J.K. Rowling': 'July 31, 1965',
 'Jane Austen': 'December 16, 1775',
 'Jim Henson': 'September 24, 1936',
 'Jorge Luis Borges': 'August 24, 1899',
 'James Baldwin': 'August 02, 1924',
 'J.R.R. Tolkien': 'January 03, 1892',
 'J.D. Salinger': 'January 01, 1919',
 'John Lennon': 'October 09, 1940',
 'Jimi Hendrix': 'November 27, 1942',
 'J.M. Barrie': 'May 09, 1860'}

In [73]:
#need to sort in dict name 

sorted_keys = sorted(author_details.keys())
sorted_dict = {key:author_details[key] for key in sorted_keys}

# Print the sorted dictionary
print(sorted_dict)

{'J.D. Salinger': 'January 01, 1919', 'J.K. Rowling': 'July 31, 1965', 'J.M. Barrie': 'May 09, 1860', 'J.R.R. Tolkien': 'January 03, 1892', 'James Baldwin': 'August 02, 1924', 'Jane Austen': 'December 16, 1775', 'Jim Henson': 'September 24, 1936', 'Jimi Hendrix': 'November 27, 1942', 'John Lennon': 'October 09, 1940', 'Jorge Luis Borges': 'August 24, 1899'}

Quotes by Albert Einstein

Find all the quotes by Albert Einstein(in the order they appear on the page) from this website
Note : Fetch data from all the pages.

Output Format :
quote1
quote2
quote3
.
.
.

link:https://quotes.toscrape.com/

In [79]:
import requests 
from bs4 import BeautifulSoup as soup 
#for one
base_url="https://quotes.toscrape.com/"
#for fist page or homepage
response=requests.get(base_url)
data=soup(response.text,'html.parser')

author=data.find_all(class_="quote")[0].find(class_="author").string
if author=='Albert Einstein':
    print(data.find(class_="text").string)

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”

In [90]:
#full code for all pages 
import requests 
from bs4 import BeautifulSoup as soup 

response=requests.get(base_url)
data=soup(response.text,'html.parser')
base_url="https://quotes.toscrape.com/"
list_of_quotes=data.find_all(class_="quote")
for i in range(len(list_of_quotes)):
    author=list_of_quotes[i].find(class_="author").string
    if author=='Albert Einstein':
        print(list_of_quotes[i].find(class_="text").string)

#for all pages 
next_page=data.find(class_="next").a["href"]
#need to stop as soon as next button stops being visible so 
while next_page is not None:
    next_page_url=base_url+data.find(class_="next").a["href"]
    response=requests.get(next_page_url)
    data=soup(response.text,'html.parser')
    list_of_quotes=data.find_all(class_="quote")
    for i in range(len(list_of_quotes)):
        author=list_of_quotes[i].find(class_="author").string
        if author=='Albert Einstein':
            print(list_of_quotes[i].find(class_="text").string)
            
    next_page=data.find(class_="next")

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
“Try not to become a man of success. Rather become a man of value.”
“If you can't explain it to a six year old, you don't understand it yourself.”
“If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales.”
“Logic will get you from A to Z; imagination will get you everywhere.”
“Any fool can know. The point is to understand.”
“Life is like riding a bicycle. To keep your balance, you must keep moving.”
“If I were not a physicist, I would probably be a musician. I often think in music. I live my daydreams in music. I see my life in terms of music.”
“Anyone who has never made a mistake has never tried anything new.”

All Categories

Print the name of all categories which are present this website.

Output Format :
 Category1 Name
 Category2 Name
 Category3 Name
 .
 .
 .
 
 link:https://books.toscrape.com/

In [105]:
import requests 
from bs4 import BeautifulSoup as soup 

response= requests.get("https://books.toscrape.com/")
data=soup(response.text,'html.parser')
catlist=data.find(class_="nav nav-list").ul.find_all("a")
for i in catlist:
    a=i.stripped_strings
    print(list(a)[0])

Travel
Mystery
Historical Fiction
Sequential Art
Classics
Philosophy
Romance
Womens Fiction
Fiction
Childrens
Religion
Nonfiction
Music
Default
Science Fiction
Sports and Games
Add a comment
Fantasy
New Adult
Young Adult
Science
Poetry
Paranormal
Art
Psychology
Autobiography
Parenting
Adult Fiction
Humor
Horror
History
Food and Drink
Christian Fiction
Business
Biography
Thriller
Contemporary
Spirituality
Academic
Self Help
Historical
Christian
Suspense
Short Stories
Novels
Health
Politics
Cultural
Erotica
Crime

First 5 Blogs

Print the title of the first 5 blogs written by Coding Ninjas
Note : Print the blog names line wise
Output Format :
blog_name_1
blog_name_2
blog_name_3
.
.

Link: https://medium.com/codingninjas-blog

In [113]:
import requests 
from bs4 import BeautifulSoup as soup 

response=requests.get('https://medium.com/codingninjas-blog')
data=soup(response.text,'html.parser')
count=0
for i in data.find_all('h3'):
    if count==5:
        break 
    print(i.string)
    count+=1

Web Development Trends to watch out for in 2020
Web Development: Interviews and You!
Get equipped for the Technical Interviews
Explore more about the projects in Web Development
5G to be a major gamechanger for Edu-tech platforms

# SELENIUM

There is one major issue with BeautifulSoup and that is we can only extract *static* content, content which doesn't require any kind of interaction, clicking on button,hyperlink,filling some form, entering some data into some text field or navigating through different webpages.

So limitation of BeautifulSoup:
1)  This process is suitable for static content only 
2)  Sometimes the data we want ti extract is hidden behind Javascript objects, objects that need to be clicked on to reveal the hidden data.

eg: from a certain website if i want to extract user comment then i need to first click on the link *show comments* -> won't display comment unless we click on it, BeautifulSoup can't help so first click to display content and then extract data ->selenium can do that

**SELENIUM** is basically a web browser **Automation Tool** which simulates a user surfing the Internet.It allows: clicking buttons, entering information on forms, searching for specific information on web pages.

Repetitive jobs can be automates like check the stock prices daily or check if results are announced on the website daily.

In [1]:
#installation 
!pip install serenium 
!pip install webdriver_manager

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/serenium/
ERROR: Could not find a version that satisfies the requirement serenium (from versions: none)
ERROR: No matching distribution found for serenium

[notice] A new release of pip is available: 23.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: webdriver_manager in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (4.0.1)
Requirement already satisfied: requests in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from webdriver_manager) (2.31.0)
Requirement already satisfied: python-dotenv in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from webdriver_manager) (1.0.0)
Requirement already satisfied: packaging in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from webdriver_manager) (23.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from requests->webdriver_manager) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from requests->webdriver_manager) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from requests->webdriver_manager) (2.0.5)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python38\lib\site-packages (from requests->webdriver_manager) (2023.7.22)

[notice] A new release of pip is available: 23.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
#importing library 
from selenium import webdriver

In [2]:
from selenium.webdriver.chrome.service import Service

In [4]:
import selenium 
selenium.__version__

'4.14.0'

In [5]:
#check chrome version from chrome://version/ or update from help-> about chrome on chrome

In [9]:
#now to launch a browser session 
service=Service(executable_path="chrome-win64/chrome.exe")
driver=webdriver.Chrome(service=service)  
# need to give path to chrome driver, i already have it in cwd 
driver #a new windom will open up

WebDriverException: Message: Can not connect to the Service chrome-win64/chrome.exe