# Book Store Analysis Using BeautifulSoup

BOOKS TO SCRAPE

link:https://books.toscrape.com/

In [67]:
#loading libraries
import requests 
from bs4 import BeautifulSoup as soup

In [68]:
#load the html data 
response=requests.get('https://books.toscrape.com/')
response

In [70]:
html=response.text
data=soup(html,'html.parser')
print(data.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="catalogue/category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="catalogue/category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>

In [71]:
#extracting title 
data.title

<title>
    All products | Books to Scrape - Sandbox
</title>

In [74]:
#to get main heading either see through inspect tool it's actually first link
data.a

In [75]:
#else 
data.header.a.string

'Books to Scrape'

In [77]:
#see on first page 20 books available -> lot of info for each book 
#title,rating,price etc
#let's extract details of this 1st book -> inspect tool ->see under class -> product_prod
b1=data.find(class_='product_pod')
b1.h3.a['title']

'A Light in the Attic'

In [78]:
b1.h3.a['href'] #actually relative url

'catalogue/a-light-in-the-attic_1000/index.html'

In [79]:
#to make complete url 
base_url='https://books.toscrape.com/'
print(base_url+b1.h3.a['href'])

https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html

In [82]:
#let's get hyperlinks for all the book 
books=data.find_all(class_='product_pod')
len(books)

20

In [83]:
for i in books:
    print(i.h3.a['href'])

catalogue/a-light-in-the-attic_1000/index.html
catalogue/tipping-the-velvet_999/index.html
catalogue/soumission_998/index.html
catalogue/sharp-objects_997/index.html
catalogue/sapiens-a-brief-history-of-humankind_996/index.html
catalogue/the-requiem-red_995/index.html
catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
catalogue/the-black-maria_991/index.html
catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html
catalogue/shakespeares-sonnets_989/index.html
catalogue/set-me-free_988/index.html
catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
catalogue/rip-it-up-and-start-again_986/index.html
catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
catalogue/olio_984/index.html
catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
catalogue/libertarianism-for-beginners_982/index.html
catalogue/its-only-the-himalayas_981/index.html

In [84]:
for i in books:
    print(base_url+i.h3.a['href'])

https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html
https://books.toscrape.com/catalogue/soumission_998/index.html
https://books.toscrape.com/catalogue/sharp-objects_997/index.html
https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html
https://books.toscrape.com/catalogue/the-requiem-red_995/index.html
https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
https://books.toscrape.com/catalogue/the-black-maria_991/index.html
https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html
https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html
https://books.toscrape.com/catalogue/set-me-free_988/index.html
https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html
https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
https://books.toscrape.com/catalogue/olio_984/index.html
https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html
https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html

**Book Names from First Page**

Print the title of all 20 books which are present on first page of this website.

 Book1 Name
 Book2 Name
 Book3 Name
 .
 .
 .

In [87]:
import requests 
from bs4 import BeautifulSoup as soup 
response=requests.get("https://books.toscrape.com/")
html=response.text 
data=soup(html,'html.parser')

In [101]:
books=data.find_all(class_='product_pod')
for i in books:
    print(i.h3.a['title'])

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas

Print the name of all categories which are present this website.

Output Format :
 Category1 Name
 Category2 Name
 Category3 Name
 .
 .
 .

In [124]:
#using inspect tool div class => side_categories => ul => nav nav-list, li =>ul => then all lists inside it

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="catalogue/category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="catalogue/category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>

In [171]:
import requests 
from bs4 import BeautifulSoup as soup 
response=requests.get("https://books.toscrape.com/")
html=response.text 
data=soup(html,'html.parser')


d={}
for i in list(data.find_all('ul')[1].li.ul.descendants):
    a=list(i.stripped_strings)
    for j in a:
        d[j]=d.get(j,0)
for k in d:
    print(k)

Travel
Mystery
Historical Fiction
Sequential Art
Classics
Philosophy
Romance
Womens Fiction
Fiction
Childrens
Religion
Nonfiction
Music
Default
Science Fiction
Sports and Games
Add a comment
Fantasy
New Adult
Young Adult
Science
Poetry
Paranormal
Art
Psychology
Autobiography
Parenting
Adult Fiction
Humor
Horror
History
Food and Drink
Christian Fiction
Business
Biography
Thriller
Contemporary
Spirituality
Academic
Self Help
Historical
Christian
Suspense
Short Stories
Novels
Health
Politics
Cultural
Erotica
Crime

In [172]:
#or 
categories_container = data.find('ul', class_='nav-list')

# Find all the list items (categories) within the container
categories = categories_container.find_all('li')

# Iterate through the categories and print their names
for category in categories[1:]:  #leaving first one since it will say "BOOKS" giving heading which is not needed
    category_name = category.a.text.strip()
    print(category_name)

Travel
Mystery
Historical Fiction
Sequential Art
Classics
Philosophy
Romance
Womens Fiction
Fiction
Childrens
Religion
Nonfiction
Music
Default
Science Fiction
Sports and Games
Add a comment
Fantasy
New Adult
Young Adult
Science
Poetry
Paranormal
Art
Psychology
Autobiography
Parenting
Adult Fiction
Humor
Horror
History
Food and Drink
Christian Fiction
Business
Biography
Thriller
Contemporary
Spirituality
Academic
Self Help
Historical
Christian
Suspense
Short Stories
Novels
Health
Politics
Cultural
Erotica
Crime

In [1]:
from bs4 import BeautifulSoup as soup 
import requests
response=requests.get("https://books.toscrape.com/")
response.status_code
html=response.text
data=soup(html,'html.parser')
for i in data.find_all(class_='side_categories'):
    print(list(i.stripped_strings)[1:])

['Travel', 'Mystery', 'Historical Fiction', 'Sequential Art', 'Classics', 'Philosophy', 'Romance', 'Womens Fiction', 'Fiction', 'Childrens', 'Religion', 'Nonfiction', 'Music', 'Default', 'Science Fiction', 'Sports and Games', 'Add a comment', 'Fantasy', 'New Adult', 'Young Adult', 'Science', 'Poetry', 'Paranormal', 'Art', 'Psychology', 'Autobiography', 'Parenting', 'Adult Fiction', 'Humor', 'Horror', 'History', 'Food and Drink', 'Christian Fiction', 'Business', 'Biography', 'Thriller', 'Contemporary', 'Spirituality', 'Academic', 'Self Help', 'Historical', 'Christian', 'Suspense', 'Short Stories', 'Novels', 'Health', 'Politics', 'Cultural', 'Erotica', 'Crime']

**Links of all the pages** 

Earlier we extracted data from first page only, this website has data of 1000 books -> available on 50 different pages. To get info about all the books we need to load data from all the pages 

The browse url should change for every get request, if you inspect the next button you will see the relative url to next pages each time you click on next , 
for page 2 it has class="next" href= "catalogue/page-2.html"  and after that just /page3.html , /page4.html. 
so 1st relative url need to have catalogue/ too in the link, other don't -> we can use an if else situation or we can once see what loads for books.toscrape.com/catalogue/page1.html rather than just for books.toscrape.com, page loading is same so better to use former one as base url

Note: if you think rather than extracting url from next we can just do base url+ page[i] i randing from 2 to 50 then this can only work here since page naming is systematic but what if page 2 has url named xyz and 3 has abc, so in that case better to make base url + relative url extracted from next button.

Also here we know limit for loop is 50 since total pages are 50 but in case we don't know then we can use while response.status_code= success that is 200

In [2]:
import requests
from bs4 import BeautifulSoup as soup

#making a list of all urls
all_urls=["https://books.toscrape.com/catalogue/page-1.html"]
current_page='https://books.toscrape.com/catalogue/page-1.html'
base_url='https://books.toscrape.com/catalogue/'
response=requests.get(current_page)
while response.status_code==200:
    data=soup(response.text,'html.parser')
    next_page=data.find(class_='next')
    next_page_url=base_url+next_page.a['href']
    print(next_page_url)
    all_urls.append(next_page_url)
    current_page=next_page_url
    response=requests.get(current_page)

https://books.toscrape.com/catalogue/page-2.html
https://books.toscrape.com/catalogue/page-3.html
https://books.toscrape.com/catalogue/page-4.html
https://books.toscrape.com/catalogue/page-5.html
https://books.toscrape.com/catalogue/page-6.html
https://books.toscrape.com/catalogue/page-7.html
https://books.toscrape.com/catalogue/page-8.html
https://books.toscrape.com/catalogue/page-9.html
https://books.toscrape.com/catalogue/page-10.html
https://books.toscrape.com/catalogue/page-11.html
https://books.toscrape.com/catalogue/page-12.html
https://books.toscrape.com/catalogue/page-13.html
https://books.toscrape.com/catalogue/page-14.html
https://books.toscrape.com/catalogue/page-15.html
https://books.toscrape.com/catalogue/page-16.html
https://books.toscrape.com/catalogue/page-17.html
https://books.toscrape.com/catalogue/page-18.html
https://books.toscrape.com/catalogue/page-19.html
https://books.toscrape.com/catalogue/page-20.html
https://books.toscrape.com/catalogue/page-21.html
https://books.toscrape.com/catalogue/page-22.html
https://books.toscrape.com/catalogue/page-23.html
https://books.toscrape.com/catalogue/page-24.html
https://books.toscrape.com/catalogue/page-25.html
https://books.toscrape.com/catalogue/page-26.html
https://books.toscrape.com/catalogue/page-27.html
https://books.toscrape.com/catalogue/page-28.html
https://books.toscrape.com/catalogue/page-29.html
https://books.toscrape.com/catalogue/page-30.html
https://books.toscrape.com/catalogue/page-31.html
https://books.toscrape.com/catalogue/page-32.html
https://books.toscrape.com/catalogue/page-33.html
https://books.toscrape.com/catalogue/page-34.html
https://books.toscrape.com/catalogue/page-35.html
https://books.toscrape.com/catalogue/page-36.html
https://books.toscrape.com/catalogue/page-37.html
https://books.toscrape.com/catalogue/page-38.html
https://books.toscrape.com/catalogue/page-39.html
https://books.toscrape.com/catalogue/page-40.html
https://books.toscrape.com/catalogue/page-41.html
https://books.toscrape.com/catalogue/page-42.html
https://books.toscrape.com/catalogue/page-43.html
https://books.toscrape.com/catalogue/page-44.html
https://books.toscrape.com/catalogue/page-45.html
https://books.toscrape.com/catalogue/page-46.html
https://books.toscrape.com/catalogue/page-47.html
https://books.toscrape.com/catalogue/page-48.html
https://books.toscrape.com/catalogue/page-49.html
https://books.toscrape.com/catalogue/page-50.html

AttributeError: 'NoneType' object has no attribute 'a'

**All Book Names**

Print the title of all books which are present on first 10 pages of this website.
Output Format :
 Book1 Name
 Book2 Name
 Book3 Name
 .
 .

In [5]:
allPages = ['http://books.toscrape.com/catalogue/page-1.html',
            'http://books.toscrape.com/catalogue/page-2.html',
            'http://books.toscrape.com/catalogue/page-3.html',
            'http://books.toscrape.com/catalogue/page-4.html',
            'http://books.toscrape.com/catalogue/page-5.html',
            'http://books.toscrape.com/catalogue/page-6.html',
            'http://books.toscrape.com/catalogue/page-7.html',
            'http://books.toscrape.com/catalogue/page-8.html',
            'http://books.toscrape.com/catalogue/page-9.html',
            'http://books.toscrape.com/catalogue/page-10.html']

import requests
from bs4 import BeautifulSoup as soup 
bookstitle=[]
for i in range(10):
    response = requests.get(allPages[i])
    data=soup(response.text,'html.parser')
    booksdata=data.find_all(class_='product_pod')
    for j in booksdata:
        bookstitle.append(j.h3.a['title'])
for d in bookstitle:
    print(d)

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas
In Her Wake
How Music Works
Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More
Chase Me (Paris Nights #2)
Black Dust
Birdsong: A Story in Pictures
America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana
Aladdin and His Wonderful Lamp
Worlds Elsewhere: Journeys Around Shakespeareâs Globe
Wall and Piece
The Four Agreements: A Practical Guide to Personal Freedom
The Five Love Languages: How to Express Heartfelt Commitment to Your Mate
The Elephant Tree
The Bear and the Piano
Sophie's World
Penny Maybe
Maude (1883-1993):She Grew Up with the country
In a Dark, Dark Wood
Behind Closed Doors
You can't bury them all: Poems
Slow States of Collapse: Poems
Reasons to Stay Alive
Private Paris (Private #10)
#HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.
Without Borders (Wanderlove #1)
When We Collided
We Love You, Charlie Freeman
Untitled Collection: Sabbath Poems 2014
Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness
Unicorn Tracks
Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink
Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRoNiCLE #2)
Throwing Rocks at the Google Bus: How Growth Became the Enemy of Prosperity
This One Summer
Thirst
The Torch Is Passed: A Harding Family Story
The Secret of Dreadwillow Carse
The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!
The Past Never Ends
The Natural History of Us (The Fine Art of Pretending #2)
The Nameless City (The Nameless City #1)
The Murder That Never Was (Forensic Instincts #5)
The Most Perfect Thing: Inside (and Outside) a Bird's Egg
The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy
The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing
The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer
The Gutsy Girl: Escapades for Your Life of Epic Adventure
The Electric Pencil: Drawings from Inside State Hospital No. 3
The Death of Humanity: and the Case for Life
The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life
The Art Forger
The Age of Genius: The Seventeenth Century and the Birth of the Modern Mind
The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution
Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up
Soul Reader
Security
Saga, Volume 6 (Saga (Collected Editions) #6)
Saga, Volume 5 (Saga (Collected Editions) #5)
Reskilling America: Learning to Labor in the Twenty-First Century
Rat Queens, Vol. 3: Demons (Rat Queens (Collected Editions) #11-15)
Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)
Princess Between Worlds (Wide-Awake Princess #5)
Pop Gun War, Volume 1: Gift
Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics
Patience
Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)
orange: The Complete Collection 1 (orange: The Complete Collection #1)
Online Marketing for Busy Authors: A Step-By-Step Guide
On a Midnight Clear
Obsidian (Lux #1)
My Paris Kitchen: Recipes and Stories
Masks and Shadows
Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed
Lumberjanes, Vol. 2: Friendship to the Max (Lumberjanes #5-8)
Lumberjanes, Vol. 1: Beware the Kitten Holy (Lumberjanes #1-4)
Lumberjanes Vol. 3: A Terrible Plan (Lumberjanes #9-12)
Layered: Baking, Building, and Styling Spectacular Cakes
Judo: Seven Steps to Black Belt (an Introductory Guide for Beginners)
Join
In the Country We Love: My Family Divided
Immunity: How Elie Metchnikoff Changed the Course of Modern Medicine
I Hate Fairyland, Vol. 1: Madly Ever After (I Hate Fairyland (Compilations) #1-5)
I am a Hero Omnibus Volume 1
How to Be Miserable: 40 Strategies You Already Use
Her Backup Boyfriend (The Sorensen Family #1)
Giant Days, Vol. 2 (Giant Days #5-8)
Forever and Forever: The Courtship of Henry Longfellow and Fanny Appleton
First and First (Five Boroughs #3)
Fifty Shades Darker (Fifty Shades #2)
Everydata: The Misinformation Hidden in the Little Data You Consume Every Day
Don't Be a Jerk: And Other Practical Advice from Dogen, Japan's Greatest Zen Master
Danganronpa Volume 1
Crown of Midnight (Throne of Glass #2)
Codename Baboushka, Volume 1: The Conclave of Death
Camp Midnight
Call the Nurse: True Stories of a Country Nurse on a Scottish Isle
Burning
Bossypants
Bitch Planet, Vol. 1: Extraordinary Machine (Bitch Planet (Collected Editions))
Avatar: The Last Airbender: Smoke and Shadow, Part 3 (Smoke and Shadow #3)
Algorithms to Live By: The Computer Science of Human Decisions
A World of Flavor: Your Gluten Free Passport
A Piece of Sky, a Grain of Rice: A Memoir in Four Meditations
A Murder in Time
A Flight of Arrows (The Pathfinders #2)
A Fierce and Subtle Poison
A Court of Thorns and Roses (A Court of Thorns and Roses #1)
(Un)Qualified: How God Uses Broken People to Do Big Things
You Are What You Love: The Spiritual Power of Habit
William Shakespeare's Star Wars: Verily, A New Hope (William Shakespeare's Star Wars #4)
Tuesday Nights in 1980
Tracing Numbers on a Train
Throne of Glass (Throne of Glass #1)
Thomas Jefferson and the Tripoli Pirates: The Forgotten War That Changed American History
Thirteen Reasons Why
The White Cat and the Monk: A Retelling of the Poem âPangur BÃ¡nâ
The Wedding Dress
The Vacationers
The Third Wave: An Entrepreneurâs Vision of the Future
The Stranger
The Shadow Hero (The Shadow Hero)
The Secret (The Secret #1)
The Regional Office Is Under Attack!
The Psychopath Test: A Journey Through the Madness Industry
The Project
The Power of Now: A Guide to Spiritual Enlightenment
The Omnivore's Dilemma: A Natural History of Four Meals
The Nerdy Nummies Cookbook: Sweet Treats for the Geek in All of Us
The Murder of Roger Ackroyd (Hercule Poirot #4)
The Mistake (Off-Campus #2)
The Matchmaker's Playbook (Wingmen Inc. #1)
The Love and Lemons Cookbook: An Apple-to-Zucchini Celebration of Impromptu Cooking
The Long Shadow of Small Ghosts: Murder and Memory in an American City
The Kite Runner
The House by the Lake
The Glittering Court (The Glittering Court #1)
The Girl on the Train
The Genius of Birds
The Emerald Mystery
The Cookies & Cups Cookbook: 125+ sweet & savory recipes reminding you to Always Eat Dessert First
The Bridge to Consciousness: I'm Writing the Bridge Between Science and Our Old and New Beliefs.
The Artist's Way: A Spiritual Path to Higher Creativity
The Art of War
The Argonauts
The 10% Entrepreneur: Live Your Startup Dream Without Quitting Your Day Job
Suddenly in Love (Lake Haven #1)
Something More Than This
Soft Apocalypse
So You've Been Publicly Shamed
Shoe Dog: A Memoir by the Creator of NIKE
Shobu Samurai, Project Aryoku (#3)
Secrets and Lace (Fatal Hearts #1)
Scarlett Epstein Hates It Here
Romero and Juliet: A Tragic Tale of Love and Zombies
Redeeming Love
Poses for Artists Volume 1 - Dynamic and Sitting Poses: An Essential Reference for Figure Drawing and the Human Form
Poems That Make Grown Women Cry
Nightingale, Sing
Night Sky with Exit Wounds
Mrs. Houdini
Modern Romance
Miss Peregrineâs Home for Peculiar Children (Miss Peregrineâs Peculiar Children #1)
Louisa: The Extraordinary Life of Mrs. Adams
Little Red
Library of Souls (Miss Peregrineâs Peculiar Children #3)
Large Print Heart of the Pride
I Had a Nice Time And Other Lies...: How to find love & sh*t like that
Hollow City (Miss Peregrineâs Peculiar Children #2)
Grumbles
Full Moon over Noahâs Ark: An Odyssey to Mount Ararat and Beyond
Frostbite (Vampire Academy #2)
Follow You Home
First Steps for New Christians (Print Edition)
Finders Keepers (Bill Hodges Trilogy #2)
Fables, Vol. 1: Legends in Exile (Fables #1)
Eureka Trivia 6.0
Drive: The Surprising Truth About What Motivates Us
Done Rubbed Out (Reightman & Bailey #1)
Doing It Over (Most Likely To #1)
Deliciously Ella Every Day: Quick and Easy Recipes for Gluten-Free Snacks, Packed Lunches, and Simple Meals

Store Data in CSV

A dedicated link is present for each book amongs 1000s on website, on going to link we can see more details abt the book like title,qty in stock,price description etc.

Let's create a dataframe of Links to websites link,title,price and qty in stock (this is not visible on homepage)

In [4]:
#ecxtracting the details for one book first 
#make a get req to homepage-> extract the book link -> extract data from that link 
#pre req 
import requests
from bs4 import BeautifulSoup as soup

In [11]:
response=requests.get('https://books.toscrape.com/')
data=soup(response.text,'html.parser')
base_url='https://books.toscrape.com/'
b1=base_url+data.find(class_='product_pod').h3.a['href']
b1  #dedicated website extracted

'https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html'

In [20]:
#now extracting required info from dedicated website 
response=requests.get(b1)
data=soup(response.text,'html.parser')
link=b1
title=data.h1.string
price=data.find(class_='price_color').string
#qty has multiple childs
qtylist=list(data.find(class_='instock availability').stripped_strings)
qty=qtylist[0]

'In stock (22 available)'

In [21]:
#printing all 
print(title)
print(link)
print(price)
print(qty)   #need to remove other text from qty and price to just get numbers

A Light in the Attic
https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
Â£51.77
In stock (22 available)

In [35]:
print(title)
print(link)
print(price)
print(qty)

A Light in the Attic
https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
51.77
22

In [39]:
#making a 2d list which we can conver to dataframe later
bookdetails=[]
bookdetails.append([title,link,price,qty])
#just two visualize appending twice 
bookdetails.append([title,link,price,qty])
bookdetails

[['A Light in the Attic',
  'https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html',
  51.77,
  22],
 ['A Light in the Attic',
  'https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html',
  51.77,
  22]]

In [40]:
import pandas as pd 

df=pd.DataFrame(bookdetails,columns=['Title','Link','Price','Quantity In Stock'])
df

,Title,Link,Price,Quantity In Stock
0,A Light in the Attic,https://books.toscrape.com/catalogue/a-light-i...,51.77,22
1,A Light in the Attic,https://books.toscrape.com/catalogue/a-light-i...,51.77,22

In [43]:
#to extract to csv 
df.to_csv('books.csv',index=False)  #to avoid index getting download

**Book Details**

Find and print the details of all books which are present on first 2 pages of this website.
All details include - Title of the book, book page url, Price (in float, without any currency or extra symbol), and quantity in stock (in integer). Save all the details in a dataframe and print in the required format.
Note: Remove the Trailing Zeros from price of book.

Output Format :
 Book1_Title Book1_Link Book1_Price Book1_Quantity
 Book2_Title Book2_Link Book2_Price Book2_Quantity
 Book3_Title Book3_Link Book3_Price Book3_Quantity
 .
 .
 .

In [2]:
#doing for first two pages 
import requests
from bs4 import BeautifulSoup as soup 
import re 
import pandas as pd

allPages = ['http://books.toscrape.com/catalogue/page-1.html',
            'http://books.toscrape.com/catalogue/page-2.html']

column_names = ['Title', 'Link', 'Price', 'Quantity in Stock']
base_url='https://books.toscrape.com/catalogue/'
book_urls=[]
for i in range(2):
    response=requests.get(allPages[i])
    data=soup(response.text,'html.parser')
    a=data.find_all(class_='product_pod')
    for k in range(len(a)):
        alink=base_url+a[k].h3.a['href']
        book_urls.append(alink)
book_urls

['https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html',
 'https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html',
 'https://books.toscrape.com/catalogue/soumission_998/index.html',
 'https://books.toscrape.com/catalogue/sharp-objects_997/index.html',
 'https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html',
 'https://books.toscrape.com/catalogue/the-requiem-red_995/index.html',
 'https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html',
 'https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html',
 'https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html',
 'https://books.toscrape.com/catalogue/the-black-maria_991/index.html',
 'https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html',
 'https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html',
 'https://books.toscrape.com/catalogue/set-me-free_988/index.html',
 'https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html',
 'https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html',
 'https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html',
 'https://books.toscrape.com/catalogue/olio_984/index.html',
 'https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html',
 'https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html',
 'https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html',
 'https://books.toscrape.com/catalogue/in-her-wake_980/index.html',
 'https://books.toscrape.com/catalogue/how-music-works_979/index.html',
 'https://books.toscrape.com/catalogue/foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html',
 'https://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html',
 'https://books.toscrape.com/catalogue/black-dust_976/index.html',
 'https://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html',
 'https://books.toscrape.com/catalogue/americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html',
 'https://books.toscrape.com/catalogue/aladdin-and-his-wonderful-lamp_973/index.html',
 'https://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html',
 'https://books.toscrape.com/catalogue/wall-and-piece_971/index.html',
 'https://books.toscrape.com/catalogue/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html',
 'https://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html',
 'https://books.toscrape.com/catalogue/the-elephant-tree_968/index.html',
 'https://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html',
 'https://books.toscrape.com/catalogue/sophies-world_966/index.html',
 'https://books.toscrape.com/catalogue/penny-maybe_965/index.html',
 'https://books.toscrape.com/catalogue/maude-1883-1993she-grew-up-with-the-country_964/index.html',
 'https://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html',
 'https://books.toscrape.com/catalogue/behind-closed-doors_962/index.html',
 'https://books.toscrape.com/catalogue/you-cant-bury-them-all-poems_961/index.html']

In [11]:
#now extracting required data 
books_details=[]
for l in book_urls:
    response=requests.get(l)
    
    if response.status_code==200:
        data=soup(response.text,'html.parser')
        link=l
        title=data.h1.string
        price=data.find(class_='price_color').string
    
        qtylist=list(data.find(class_='instock availability').stripped_strings)
        qty=qtylist[0]
        price=float((re.search('[\d.]+',price)).group())
        price = "{:.2f}".format(price)
        qty=int((re.search('\d+',qty)).group())
        

        books_details.append([title,link,price,qty])
books_details

[['A Light in the Attic',
  'https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html',
  '51.77',
  22],
 ['Tipping the Velvet',
  'https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html',
  '53.74',
  20],
 ['Soumission',
  'https://books.toscrape.com/catalogue/soumission_998/index.html',
  '50.10',
  20],
 ['Sharp Objects',
  'https://books.toscrape.com/catalogue/sharp-objects_997/index.html',
  '47.82',
  20],
 ['Sapiens: A Brief History of Humankind',
  'https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html',
  '54.23',
  20],
 ['The Requiem Red',
  'https://books.toscrape.com/catalogue/the-requiem-red_995/index.html',
  '22.65',
  19],
 ['The Dirty Little Secrets of Getting Your Dream Job',
  'https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html',
  '33.34',
  19],
 ['The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
  'https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html',
  '17.93',
  19],
 ['The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  'https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html',
  '22.60',
  19],
 ['The Black Maria',
  'https://books.toscrape.com/catalogue/the-black-maria_991/index.html',
  '52.15',
  19],
 ['Starving Hearts (Triangular Trade Trilogy, #1)',
  'https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html',
  '13.99',
  19],
 ["Shakespeare's Sonnets",
  'https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html',
  '20.66',
  19],
 ['Set Me Free',
  'https://books.toscrape.com/catalogue/set-me-free_988/index.html',
  '17.46',
  19],
 ["Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)",
  'https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html',
  '52.29',
  19],
 ['Rip it Up and Start Again',
  'https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html',
  '35.02',
  19],
 ['Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
  'https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html',
  '57.25',
  19],
 ['Olio',
  'https://books.toscrape.com/catalogue/olio_984/index.html',
  '23.88',
  19],
 ['Mesaerion: The Best Science Fiction Stories 1800-1849',
  'https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html',
  '37.59',
  19],
 ['Libertarianism for Beginners',
  'https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html',
  '51.33',
  19],
 ["It's Only the Himalayas",
  'https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html',
  '45.17',
  19],
 ['In Her Wake',
  'https://books.toscrape.com/catalogue/in-her-wake_980/index.html',
  '12.84',
  19],
 ['How Music Works',
  'https://books.toscrape.com/catalogue/how-music-works_979/index.html',
  '37.32',
  19],
 ['Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More',
  'https://books.toscrape.com/catalogue/foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html',
  '30.52',
  19],
 ['Chase Me (Paris Nights #2)',
  'https://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html',
  '25.27',
  19],
 ['Black Dust',
  'https://books.toscrape.com/catalogue/black-dust_976/index.html',
  '34.53',
  19],
 ['Birdsong: A Story in Pictures',
  'https://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html',
  '54.64',
  19],
 ["America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana",
  'https://books.toscrape.com/catalogue/americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html',
  '22.50',
  19],
 ['Aladdin and His Wonderful Lamp',
  'https://books.toscrape.com/catalogue/aladdin-and-his-wonderful-lamp_973/index.html',
  '53.13',
  19],
 ['Worlds Elsewhere: Journeys Around Shakespeareâ\x80\x99s Globe',
  'https://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html',
  '40.30',
  18],
 ['Wall and Piece',
  'https://books.toscrape.com/catalogue/wall-and-piece_971/index.html',
  '44.18',
  18],
 ['The Four Agreements: A Practical Guide to Personal Freedom',
  'https://books.toscrape.com/catalogue/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html',
  '17.66',
  18],
 ['The Five Love Languages: How to Express Heartfelt Commitment to Your Mate',
  'https://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html',
  '31.05',
  18],
 ['The Elephant Tree',
  'https://books.toscrape.com/catalogue/the-elephant-tree_968/index.html',
  '23.82',
  18],
 ['The Bear and the Piano',
  'https://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html',
  '36.89',
  18],
 ["Sophie's World",
  'https://books.toscrape.com/catalogue/sophies-world_966/index.html',
  '15.94',
  18],
 ['Penny Maybe',
  'https://books.toscrape.com/catalogue/penny-maybe_965/index.html',
  '33.29',
  18],
 ['Maude (1883-1993):She Grew Up with the country',
  'https://books.toscrape.com/catalogue/maude-1883-1993she-grew-up-with-the-country_964/index.html',
  '18.02',
  18],
 ['In a Dark, Dark Wood',
  'https://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html',
  '19.63',
  18],
 ['Behind Closed Doors',
  'https://books.toscrape.com/catalogue/behind-closed-doors_962/index.html',
  '52.22',
  18],
 ["You can't bury them all: Poems",
  'https://books.toscrape.com/catalogue/you-cant-bury-them-all-poems_961/index.html',
  '33.63',
  17]]

In [12]:
df=pd.DataFrame(books_details,columns=column_names)
df

,Title,Link,Price,Quantity in Stock
0,A Light in the Attic,https://books.toscrape.com/catalogue/a-light-i...,51.77,22
1,Tipping the Velvet,https://books.toscrape.com/catalogue/tipping-t...,53.74,20
2,Soumission,https://books.toscrape.com/catalogue/soumissio...,50.10,20
3,Sharp Objects,https://books.toscrape.com/catalogue/sharp-obj...,47.82,20
4,Sapiens: A Brief History of Humankind,https://books.toscrape.com/catalogue/sapiens-a...,54.23,20
5,The Requiem Red,https://books.toscrape.com/catalogue/the-requi...,22.65,19
6,The Dirty Little Secrets of Getting Your Dream...,https://books.toscrape.com/catalogue/the-dirty...,33.34,19
7,The Coming Woman: A Novel Based on the Life of...,https://books.toscrape.com/catalogue/the-comin...,17.93,19
8,The Boys in the Boat: Nine Americans and Their...,https://books.toscrape.com/catalogue/the-boys-...,22.60,19
9,The Black Maria,https://books.toscrape.com/catalogue/the-black...,52.15,19
10,"Starving Hearts (Triangular Trade Trilogy, #1)",https://books.toscrape.com/catalogue/starving-...,13.99,19
11,Shakespeare's Sonnets,https://books.toscrape.com/catalogue/shakespea...,20.66,19
12,Set Me Free,https://books.toscrape.com/catalogue/set-me-fr...,17.46,19
13,Scott Pilgrim's Precious Little Life (Scott Pi...,https://books.toscrape.com/catalogue/scott-pil...,52.29,19
14,Rip it Up and Start Again,https://books.toscrape.com/catalogue/rip-it-up...,35.02,19
15,Our Band Could Be Your Life: Scenes from the A...,https://books.toscrape.com/catalogue/our-band-...,57.25,19
16,Olio,https://books.toscrape.com/catalogue/olio_984/...,23.88,19
17,Mesaerion: The Best Science Fiction Stories 18...,https://books.toscrape.com/catalogue/mesaerion...,37.59,19
18,Libertarianism for Beginners,https://books.toscrape.com/catalogue/libertari...,51.33,19
19,It's Only the Himalayas,https://books.toscrape.com/catalogue/its-only-...,45.17,19
20,In Her Wake,https://books.toscrape.com/catalogue/in-her-wa...,12.84,19
21,How Music Works,https://books.toscrape.com/catalogue/how-music...,37.32,19
22,Foolproof Preserving: A Guide to Small Batch J...,https://books.toscrape.com/catalogue/foolproof...,30.52,19
23,Chase Me (Paris Nights #2),https://books.toscrape.com/catalogue/chase-me-...,25.27,19
24,Black Dust,https://books.toscrape.com/catalogue/black-dus...,34.53,19
25,Birdsong: A Story in Pictures,https://books.toscrape.com/catalogue/birdsong-...,54.64,19
26,America's Cradle of Quarterbacks: Western Penn...,https://books.toscrape.com/catalogue/americas-...,22.50,19
27,Aladdin and His Wonderful Lamp,https://books.toscrape.com/catalogue/aladdin-a...,53.13,19
28,Worlds Elsewhere: Journeys Around Shakespeareâ...,https://books.toscrape.com/catalogue/worlds-el...,40.30,18
29,Wall and Piece,https://books.toscrape.com/catalogue/wall-and-...,44.18,18
30,The Four Agreements: A Practical Guide to Pers...,https://books.toscrape.com/catalogue/the-four-...,17.66,18
31,The Five Love Languages: How to Express Heartf...,https://books.toscrape.com/catalogue/the-five-...,31.05,18
32,The Elephant Tree,https://books.toscrape.com/catalogue/the-eleph...,23.82,18
33,The Bear and the Piano,https://books.toscrape.com/catalogue/the-bear-...,36.89,18
34,Sophie's World,https://books.toscrape.com/catalogue/sophies-w...,15.94,18
35,Penny Maybe,https://books.toscrape.com/catalogue/penny-may...,33.29,18
36,Maude (1883-1993):She Grew Up with the country,https://books.toscrape.com/catalogue/maude-188...,18.02,18
37,"In a Dark, Dark Wood",https://books.toscrape.com/catalogue/in-a-dark...,19.63,18
38,Behind Closed Doors,https://books.toscrape.com/catalogue/behind-cl...,52.22,18
39,You can't bury them all: Poems,https://books.toscrape.com/catalogue/you-cant-...,33.63,17

In [13]:
for detail in books_details:
    print(*detail)

A Light in the Attic https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html 51.77 22
Tipping the Velvet https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html 53.74 20
Soumission https://books.toscrape.com/catalogue/soumission_998/index.html 50.10 20
Sharp Objects https://books.toscrape.com/catalogue/sharp-objects_997/index.html 47.82 20
Sapiens: A Brief History of Humankind https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html 54.23 20
The Requiem Red https://books.toscrape.com/catalogue/the-requiem-red_995/index.html 22.65 19
The Dirty Little Secrets of Getting Your Dream Job https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html 33.34 19
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html 17.93 19
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html 22.60 19
The Black Maria https://books.toscrape.com/catalogue/the-black-maria_991/index.html 52.15 19
Starving Hearts (Triangular Trade Trilogy, #1) https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html 13.99 19
Shakespeare's Sonnets https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html 20.66 19
Set Me Free https://books.toscrape.com/catalogue/set-me-free_988/index.html 17.46 19
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1) https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html 52.29 19
Rip it Up and Start Again https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html 35.02 19
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991 https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html 57.25 19
Olio https://books.toscrape.com/catalogue/olio_984/index.html 23.88 19
Mesaerion: The Best Science Fiction Stories 1800-1849 https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html 37.59 19
Libertarianism for Beginners https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html 51.33 19
It's Only the Himalayas https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html 45.17 19
In Her Wake https://books.toscrape.com/catalogue/in-her-wake_980/index.html 12.84 19
How Music Works https://books.toscrape.com/catalogue/how-music-works_979/index.html 37.32 19
Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More https://books.toscrape.com/catalogue/foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html 30.52 19
Chase Me (Paris Nights #2) https://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html 25.27 19
Black Dust https://books.toscrape.com/catalogue/black-dust_976/index.html 34.53 19
Birdsong: A Story in Pictures https://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html 54.64 19
America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana https://books.toscrape.com/catalogue/americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html 22.50 19
Aladdin and His Wonderful Lamp https://books.toscrape.com/catalogue/aladdin-and-his-wonderful-lamp_973/index.html 53.13 19
Worlds Elsewhere: Journeys Around Shakespeareâs Globe https://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html 40.30 18
Wall and Piece https://books.toscrape.com/catalogue/wall-and-piece_971/index.html 44.18 18
The Four Agreements: A Practical Guide to Personal Freedom https://books.toscrape.com/catalogue/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html 17.66 18
The Five Love Languages: How to Express Heartfelt Commitment to Your Mate https://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html 31.05 18
The Elephant Tree https://books.toscrape.com/catalogue/the-elephant-tree_968/index.html 23.82 18
The Bear and the Piano https://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html 36.89 18
Sophie's World https://books.toscrape.com/catalogue/sophies-world_966/index.html 15.94 18
Penny Maybe https://books.toscrape.com/catalogue/penny-maybe_965/index.html 33.29 18
Maude (1883-1993):She Grew Up with the country https://books.toscrape.com/catalogue/maude-1883-1993she-grew-up-with-the-country_964/index.html 18.02 18
In a Dark, Dark Wood https://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html 19.63 18
Behind Closed Doors https://books.toscrape.com/catalogue/behind-closed-doors_962/index.html 52.22 18
You can't bury them all: Poems https://books.toscrape.com/catalogue/you-cant-bury-them-all-poems_961/index.html 33.63 17

In [20]:
for index, row in df.iterrows():
    for column, value in row.items():
        print(value,end=" ")
    print()

A Light in the Attic https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html 51.77 22
Tipping the Velvet https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html 53.74 20
Soumission https://books.toscrape.com/catalogue/soumission_998/index.html 50.10 20
Sharp Objects https://books.toscrape.com/catalogue/sharp-objects_997/index.html 47.82 20
Sapiens: A Brief History of Humankind https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html 54.23 20
The Requiem Red https://books.toscrape.com/catalogue/the-requiem-red_995/index.html 22.65 19
The Dirty Little Secrets of Getting Your Dream Job https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html 33.34 19
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html 17.93 19
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html 22.60 19
The Black Maria https://books.toscrape.com/catalogue/the-black-maria_991/index.html 52.15 19
Starving Hearts (Triangular Trade Trilogy, #1) https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html 13.99 19
Shakespeare's Sonnets https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html 20.66 19
Set Me Free https://books.toscrape.com/catalogue/set-me-free_988/index.html 17.46 19
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1) https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html 52.29 19
Rip it Up and Start Again https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html 35.02 19
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991 https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html 57.25 19
Olio https://books.toscrape.com/catalogue/olio_984/index.html 23.88 19
Mesaerion: The Best Science Fiction Stories 1800-1849 https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html 37.59 19
Libertarianism for Beginners https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html 51.33 19
It's Only the Himalayas https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html 45.17 19
In Her Wake https://books.toscrape.com/catalogue/in-her-wake_980/index.html 12.84 19
How Music Works https://books.toscrape.com/catalogue/how-music-works_979/index.html 37.32 19
Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More https://books.toscrape.com/catalogue/foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html 30.52 19
Chase Me (Paris Nights #2) https://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html 25.27 19
Black Dust https://books.toscrape.com/catalogue/black-dust_976/index.html 34.53 19
Birdsong: A Story in Pictures https://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html 54.64 19
America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana https://books.toscrape.com/catalogue/americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html 22.50 19
Aladdin and His Wonderful Lamp https://books.toscrape.com/catalogue/aladdin-and-his-wonderful-lamp_973/index.html 53.13 19
Worlds Elsewhere: Journeys Around Shakespeareâs Globe https://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html 40.30 18
Wall and Piece https://books.toscrape.com/catalogue/wall-and-piece_971/index.html 44.18 18
The Four Agreements: A Practical Guide to Personal Freedom https://books.toscrape.com/catalogue/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html 17.66 18
The Five Love Languages: How to Express Heartfelt Commitment to Your Mate https://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html 31.05 18
The Elephant Tree https://books.toscrape.com/catalogue/the-elephant-tree_968/index.html 23.82 18
The Bear and the Piano https://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html 36.89 18
Sophie's World https://books.toscrape.com/catalogue/sophies-world_966/index.html 15.94 18
Penny Maybe https://books.toscrape.com/catalogue/penny-maybe_965/index.html 33.29 18
Maude (1883-1993):She Grew Up with the country https://books.toscrape.com/catalogue/maude-1883-1993she-grew-up-with-the-country_964/index.html 18.02 18
In a Dark, Dark Wood https://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html 19.63 18
Behind Closed Doors https://books.toscrape.com/catalogue/behind-closed-doors_962/index.html 52.22 18
You can't bury them all: Poems https://books.toscrape.com/catalogue/you-cant-bury-them-all-poems_961/index.html 33.63 17

In [9]:
#saving to csv file 
df.to_csv("Bookdetailsfirsttwopages.csv",index=False) #.csv for proper format

In [52]:
#same ans as below but below one worked in codezen 
from bs4 import BeautifulSoup
import pandas as pd
import requests
import re

allPages = ['http://books.toscrape.com/catalogue/page-1.html','http://books.toscrape.com/catalogue/page-2.html']
column_names = ['Title', 'Link', 'Price', 'Quantity in Stock']
base_url = 'http://books.toscrape.com/catalogue/'

allBooks=[]
for i in allPages:
    response = requests.get(i)
    data = BeautifulSoup(response.text, 'html.parser')
    book = data.find_all(class_='product_pod')
    for i in book:
        b_url = base_url + i.h3.a['href']
        allBooks.append(b_url)

        
Book_details=[]
for i in allBooks:
    response = requests.get(i)
    data = BeautifulSoup(response.text, 'html.parser')
    title = data.h1.string
    price = data.find(class_='price_color').string
    qty = data.find(class_='instock availability')
    qty = qty.contents[-1].strip()
    qty = int(re.search('\d+',qty).group())
    price = float(re.search('[\d.]+',price).group())
    Book_details.append([title, i, price, qty])
    
#for i in Book_details:
#print(*i)
df = pd.DataFrame(Book_details,columns=column_names)
for i in range(len(df)):
    print(df['Title'][i],df['Link'][i],df['Price'][i],df['Quantity in Stock'][i])

A Light in the Attic http://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html 51.77 22
Tipping the Velvet http://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html 53.74 20
Soumission http://books.toscrape.com/catalogue/soumission_998/index.html 50.1 20
Sharp Objects http://books.toscrape.com/catalogue/sharp-objects_997/index.html 47.82 20
Sapiens: A Brief History of Humankind http://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html 54.23 20
The Requiem Red http://books.toscrape.com/catalogue/the-requiem-red_995/index.html 22.65 19
The Dirty Little Secrets of Getting Your Dream Job http://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html 33.34 19
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull http://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html 17.93 19
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics http://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html 22.6 19
The Black Maria http://books.toscrape.com/catalogue/the-black-maria_991/index.html 52.15 19
Starving Hearts (Triangular Trade Trilogy, #1) http://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html 13.99 19
Shakespeare's Sonnets http://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html 20.66 19
Set Me Free http://books.toscrape.com/catalogue/set-me-free_988/index.html 17.46 19
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1) http://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html 52.29 19
Rip it Up and Start Again http://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html 35.02 19
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991 http://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html 57.25 19
Olio http://books.toscrape.com/catalogue/olio_984/index.html 23.88 19
Mesaerion: The Best Science Fiction Stories 1800-1849 http://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html 37.59 19
Libertarianism for Beginners http://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html 51.33 19
It's Only the Himalayas http://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html 45.17 19
In Her Wake http://books.toscrape.com/catalogue/in-her-wake_980/index.html 12.84 19
How Music Works http://books.toscrape.com/catalogue/how-music-works_979/index.html 37.32 19
Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More http://books.toscrape.com/catalogue/foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html 30.52 19
Chase Me (Paris Nights #2) http://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html 25.27 19
Black Dust http://books.toscrape.com/catalogue/black-dust_976/index.html 34.53 19
Birdsong: A Story in Pictures http://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html 54.64 19
America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana http://books.toscrape.com/catalogue/americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html 22.5 19
Aladdin and His Wonderful Lamp http://books.toscrape.com/catalogue/aladdin-and-his-wonderful-lamp_973/index.html 53.13 19
Worlds Elsewhere: Journeys Around Shakespeareâs Globe http://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html 40.3 18
Wall and Piece http://books.toscrape.com/catalogue/wall-and-piece_971/index.html 44.18 18
The Four Agreements: A Practical Guide to Personal Freedom http://books.toscrape.com/catalogue/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html 17.66 18
The Five Love Languages: How to Express Heartfelt Commitment to Your Mate http://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html 31.05 18
The Elephant Tree http://books.toscrape.com/catalogue/the-elephant-tree_968/index.html 23.82 18
The Bear and the Piano http://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html 36.89 18
Sophie's World http://books.toscrape.com/catalogue/sophies-world_966/index.html 15.94 18
Penny Maybe http://books.toscrape.com/catalogue/penny-maybe_965/index.html 33.29 18
Maude (1883-1993):She Grew Up with the country http://books.toscrape.com/catalogue/maude-1883-1993she-grew-up-with-the-country_964/index.html 18.02 18
In a Dark, Dark Wood http://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html 19.63 18
Behind Closed Doors http://books.toscrape.com/catalogue/behind-closed-doors_962/index.html 52.22 18
You can't bury them all: Poems http://books.toscrape.com/catalogue/you-cant-bury-them-all-poems_961/index.html 33.63 17

All Categories

Print the name of all categories which are present this website.

Output Format :
 Category1 Name
 Category2 Name
 Category3 Name
 .
 .
 .
 
 link:https://books.toscrape.com/

In [105]:
import requests 
from bs4 import BeautifulSoup as soup 

response= requests.get("https://books.toscrape.com/")
data=soup(response.text,'html.parser')
catlist=data.find(class_="nav nav-list").ul.find_all("a")
for i in catlist:
    a=i.stripped_strings
    print(list(a)[0])

Travel
Mystery
Historical Fiction
Sequential Art
Classics
Philosophy
Romance
Womens Fiction
Fiction
Childrens
Religion
Nonfiction
Music
Default
Science Fiction
Sports and Games
Add a comment
Fantasy
New Adult
Young Adult
Science
Poetry
Paranormal
Art
Psychology
Autobiography
Parenting
Adult Fiction
Humor
Horror
History
Food and Drink
Christian Fiction
Business
Biography
Thriller
Contemporary
Spirituality
Academic
Self Help
Historical
Christian
Suspense
Short Stories
Novels
Health
Politics
Cultural
Erotica
Crime